<?php
$projects["series"][] = [

    "title"       => "Reversals",
    "subtitle"    => "",
    "slug"        => "reverse_profiles",
    "description" => "People’s profile silhouettes are computationally reversed.",
    "works"       => [
        [
            "id"          => "jkk_",
            "title"       => "Reverse Ryan & Betsy",
            "subtitle"    => "",
            "slug"        => "ryan-betsy",
            "medium"      => "",
            "date"        => "",
            "height"      => "",
            "width"       => "",
            "units"       => "",
            "description" => "The silhouettes of Ryan & Betsy are computationally reversed",
            "status"      => "",
            "notes"       => "",
        ],
        [
            "id"          => "jkk_",
            "title"       => "Ignobel Award",
            "subtitle"    => "",
            "slug"        => "ignobel-award",
            "medium"      => "",
            "date"        => "",
            "height"      => "",
            "width"       => "",
            "units"       => "",
            "description" => "The silhouette on the Nobel Prize is computationally reversed",
            "status"      => "",
            "notes"       => "",
        ],
        [
            "id"          => "jkk_",
            "title"       => "Reverse Keetra & JK",
            "subtitle"    => "",
            "slug"        => "keetra-jk",
            "medium"      => "",
            "date"        => "",
            "height"      => "",
            "width"       => "",
            "units"       => "",
            "description" => "The silhouettes of Keetra & JK are computationally reversed",
            "status"      => "",
            "notes"       => "",
        ],
        [
            "id"          => "jkk_",
            "title"       => "Turnaround Coins",
            "subtitle"    => "",
            "slug"        => "turnaround-coins",
            "medium"      => "",
            "date"        => "",
            "height"      => "",
            "width"       => "",
            "units"       => "",
            "description" => "The silhouettes on coins are computationally reversed",
            "status"      => "",
            "notes"       => "",
        ],
        [
            "id"          => "jkk_",
            "title"       => "Reverse Paulette & Sid",
            "subtitle"    => "",
            "slug"        => "paulette-sid",
            "medium"      => "",
            "date"        => "",
            "height"      => "",
            "width"       => "",
            "units"       => "",
            "description" => "The silhouettes of Paulette & Sid are computationally reversed",
            "status"      => "",
            "notes"       => "",
        ],
        [
            "id"          => "jkk_",
            "title"       => "Looking Without Paying Attention",
            "subtitle"    => "",
            "slug"        => "mccain-obama",
            "medium"      => "",
            "date"        => "",
            "height"      => "",
            "width"       => "",
            "units"       => "",
            "description" => "A typical across the aisle meeting in American politics",
            "status"      => "",
            "notes"       => "",
        ],
    ],

];
?>
