<?php
$projects["series"][] = [

    "id"          => "jkk_",
    "title"       => "I’ve Been Thinking of You for a While",
    "subtitle"    => "",
    "slug"        => "layered_wax",
    "notes"       => "collab with Keetra Dean Dixon",
    "works"       => [
        [
            "id"          => "jkk_",
            "title"       => "THEN AGAIN",
            "subtitle"    => "",
            "slug"        => "then_again",
            "medium"      => "wax and acrylic paint",
            "date"        => "2017",
            "height"      => "26",
            "width"       => "51.5",
            "depth"       => "7.5",
            "units"       => "in",
            "description" => "<p>commissioned by the Stedelijk Musuem Breda for <cite class=\"exhibition\">Wonderlijk weefsel</cite> exhibtion</p><p>collab with <a href=\"http://fromkeetra.com\">Keetra Dean Dixon</a></p>",
            "status"      => "Stedelijk Musuem Breda",
        ],
        [
            "id"          => "jkk_",
            "title"       => "THEN AGAIN (Specimen #1)",
            "subtitle"    => "",
            "slug"        => "then_again-specimen_1",
            "medium"      => "wax and acrylic paint",
            "date"        => "2017",
            "height"      => "",
            "width"       => "",
            "depth"       => "",
            "units"       => "",
            "status"      => "TBD",
        ],
        [
            "id"          => "jkk_",
            "title"       => "THEN AGAIN (Specimen #2)",
            "subtitle"    => "",
            "slug"        => "then_again-specimen_1",
            "medium"      => "wax and acrylic paint",
            "date"        => "2017",
            "height"      => "",
            "width"       => "",
            "depth"       => "",
            "units"       => "",
            "status"      => "TBD",
        ],
        [
            "id"          => "jkk_",
            "title"       => "Suddenly",
            "subtitle"    => "",
            "slug"        => "suddenly",
            "medium"      => "wax and acrylic paint",
            "date"        => "2011",
            "height"      => "",
            "width"       => "",
            "depth"       => "",
            "units"       => "",
            "status"      => "D.C. person?",
            "notes"       => "",
        ],
        [
            "id"          => "jkk_",
            "title"       => "Suddenly (Specimen #1)",
            "subtitle"    => "",
            "slug"        => "suddenly",
            "medium"      => "wax and acrylic paint",
            "date"        => "2011",
            "height"      => "",
            "width"       => "",
            "depth"       => "",
            "units"       => "",
            "status"      => "",
            "notes"       => "",
        ],
        [
            "id"          => "jkk_",
            "title"       => "Suddenly (Specimen #2)",
            "subtitle"    => "",
            "slug"        => "suddenly",
            "medium"      => "wax and acrylic paint",
            "date"        => "2011",
            "height"      => "",
            "width"       => "",
            "depth"       => "",
            "units"       => "",
            "status"      => "gift? sold?",
            "notes"       => "",
        ],
        [
            "id"          => "jkk_",
            "title"       => "And Yet",
            "subtitle"    => "",
            "slug"        => "and-yet",
            "medium"      => "wax and acrylic paint",
            "date"        => "2011",
            "height"      => "",
            "width"       => "",
            "depth"       => "",
            "units"       => "",
            "byline"      => "",
            "status"      => "Chattanooga",
            "notes"       => "",
        ],
        [
            "id"          => "jkk_",
            "title"       => "And Yet (Specimen #1)",
            "subtitle"    => "",
            "slug"        => "and-yet",
            "medium"      => "wax and acrylic paint",
            "date"        => "2011",
            "height"      => "",
            "width"       => "",
            "depth"       => "",
            "units"       => "",
            "byline"      => "",
            "status"      => "",
            "notes"       => "",
        ],
        [
            "id"          => "jkk_",
            "title"       => "And Yet (Specimen #2)",
            "subtitle"    => "",
            "slug"        => "and-yet",
            "medium"      => "wax and acrylic paint",
            "date"        => "2011",
            "height"      => "",
            "width"       => "",
            "depth"       => "",
            "units"       => "",
            "byline"      => "",
            "status"      => "",
            "notes"       => "",
        ],
        [
            "id"          => "jkk_",
            "title"       => "Only",
            "subtitle"    => "",
            "slug"        => "only",
            "medium"      => "wax, acrylic paint, cinder blocks, and oil paint",
            "date"        => "2011",
            "height"      => "48",
            "width"       => "21",
            "depth"       => "12",
            "units"       => "in",
            "status"      => "garage",
            "notes"       => "baltimore exhibition",
        ],
        [
            "id"          => "jkk_",
            "title"       => "Only (Specimen)",
            "subtitle"    => "",
            "slug"        => "only_specimen",
            "medium"      => "wax, acrylic paint",
            "date"        => "2011",
            "height"      => "",
            "width"       => "",
            "depth"       => "",
            "units"       => "in",
            "status"      => "sold",
            "notes"       => "",
        ],
        [
            "id"          => "jkk_",
            "title"       => "Become",
            "subtitle"    => "(orange)",
            "slug"        => "become-2",
            "medium"      => "wax, acrylic paint, and spray foam",
            "date"        => "2009",
            "height"      => "24",
            "width"       => "13",
            "depth"       => "7",
            "units"       => "in",
            "status"      => "garage",
            "notes"       => "MAD Museum exhibition, Obama exhibition",
        ],
        [
            "id"          => "jkk_",
            "title"       => "Become (Specimen)",
            "subtitle"    => "",
            "slug"        => "become_2_specimen",
            "medium"      => "wax and acrylic paint",
            "date"        => "2009",
            "height"      => "",
            "width"       => "",
            "depth"       => "",
            "units"       => "in",
            "status"      => "nfs",
            "notes"       => "MAD Museum exhibition, Obama exhibition",
        ],
        [
            "id"          => "jkk_",
            "title"       => "Become",
            "subtitle"    => "(green)",
            "slug"        => "become",
            "medium"      => "wax, acrylic paint, and spray foam",
            "date"        => "2009",
            "height"      => "24",
            "width"       => "13",
            "depth"       => "7",
            "units"       => "in",
            "status"      => "destroyed",
            "notes"       => "",
        ],
        [
            "id"          => "jkk_",
            "title"       => "Throughout",
            "subtitle"    => "",
            "slug"        => "throughout",
            "medium"      => "wax, acrylic paint, and spray foam",
            "date"        => "2008",
            "height"      => "54",
            "width"       => "14",
            "depth"       => "6",
            "units"       => "in",
            "status"      => "Naona/destroyed",
            "notes"       => "3d type exhibition",
        ],
    ],

];
?>
