<?php
$projects["series"][] = [

	"title"       => "It Takes Me a Long Time to Say Nothing",
	"subtitle"    => "dot drawings",
	"slug"        => "dots_dots_dots",
    "description" => "Lots & lots of dots in spots",
    "notes"       => "included in Chattanooga exhibition.",
    "to_dos"      => "<li>Readhere stickers to paper</li>
		<li>grind paint off rods</li>
		<li>repaint rods for hanging</li>
		<li>get other binder coil colors?</li>
		<li>reshoot in good light</li>
		<li>finish __FUL</li>
		<li>more... big dots</li>",

	"works"     => [
        [
            "id"          => "jkk_200900_1_u",
            "title"       => "",
            "subtitle"    => "S",
            "slug"        => "dots_s",
            "medium"      => "sticker dots on paper",
            "date"        => "2009",
            "height"      => "",
            "width"       => "",
            "units"       => "",
            "location"    => "in a studio pile somewhere",
            "status"      => "",
            "notes"       => "",
            "image"       => "",
        ],
        [
            "id"          => "jkk_201408_7_u",
            "title"       => "",
            "subtitle"    => "...EST",
            "slug"        => "dots_est",
            "medium"      => "sticker dots on paper",
            "date"        => "2014",
            "height"      => "12",
            "width"       => "18",
            "units"       => "in",
            "location"    => "studio",
            "status"      => "",
            "notes"       => "",
            "image"       => "jk_keller-201408_7_u-dots_est-web-temp.jpg",
        ],
		[
			"id"          => "jkk_201408_3_u",
			"title"       => "",
			"subtitle"    => "...US...",
			"slug"        => "dots_us",
			"medium"      => "sticker dots on paper",
			"date"        => "2014",
			"height"      => "12",
			"width"       => "18",
			"units"       => "in",
			"location"    => "K & U?",
            "status"      => "gift",
			"notes"       => "",
            "image"       => "jk_keller-201408_3_u-dots_us-web-temp.jpg",
		],
		[
			"id"          => "jkk_201408_6_u",
			"title"       => "",
			"subtitle"    => "AND",
			"slug"        => "dots_and",
			"medium"      => "sticker dots on paper",
			"date"        => "2014",
			"height"      => "18",
			"width"       => "24",
			"units"       => "in",
			"location"    => "JD?",
            "status"      => "gift",
			"notes"       => "",
            "image"       => "jk_keller-201408_6_u-dots_and-web-temp.jpg",
		],
		[
			"id"          => "jkk_201509_3_u",
			"title"       => "",
			"subtitle"    => "H",
			"slug"        => "dots_h",
			"medium"      => "sticker dots on paper",
			"date"        => "2015",
			"height"      => "8.25",
			"width"       => "6.25",
			"units"       => "in",
			"location"    => "Chattanooga person",
            "status"      => "gift",
			"notes"       => "2015 Sep 18",
            "image"       => "jk_keller-201509_3_u-dots_h-web.jpg",
		],
		[
			"id"          => "jkk_201408_4_u",
			"title"       => "",
			"subtitle"    => "BUT",
			"slug"        => "dots_but",
			"medium"      => "sticker dots on paper",
			"date"        => "2014",
			"height"      => "18",
			"width"       => "24",
			"units"       => "in",
            "location"    => "studio",
            "status"      => "",
			"notes"       => "",
            "image"       => "jk_keller-201408_4_u-dots_but-web-temp.jpg",
		],
        [
            "id"          => "jkk_201408_5_u",
            "title"       => "",
            "subtitle"    => "MIS...",
            "slug"        => "dots_mis",
            "medium"      => "sticker dots on paper",
            "date"        => "2014",
            "height"      => "12",
            "width"       => "18",
            "units"       => "in",
            "location"    => "studio",
            "status"      => "",
            "notes"       => "",
            "image"       => "jk_keller-201408_5_u-dots_mis-web-temp.jpg",
        ],
        [
            "id"          => "jkk_201408_2_u",
            "title"       => "",
            "subtitle"    => "...FUL",
            "slug"        => "dots_ful",
            "medium"      => "sticker dots on paper",
            "date"        => "2014",
            "height"      => "",
            "width"       => "",
            "units"       => "",
            "location"    => "studio",
            "status"      => "to finish",
            "notes"       => "",
            "image"       => "",
        ],
		[
			"id"          => "jkk_201408_1_u",
			"title"       => "",
			"subtitle"    => "RE...",
			"slug"        => "dots_re",
			"medium"      => "sticker dots on paper",
			"date"        => "2014",
			"height"      => "12",
			"width"       => "18",
			"units"       => "in",
            "location"    => "studio",
            "status"      => "",
			"notes"       => "",
            "image"       => "jk_keller-201408_1_u-dots_re-web-temp.jpg",
		],
		[
			"id"          => "jkk_201404_1_u",
			"title"       => "",
			"subtitle"    => "Infinity",
			"slug"        => "dots_infinity",
			"medium"      => "sticker dots on paper",
			"date"        => "2014",
			"height"      => "5",
			"width"       => "7",
			"units"       => "in",
			"location"    => "England auction",
            "status"      => "donation",
			"notes"       => "",
            "image"       => "jk_keller-201404_1_u-dots_infinity-web.jpg",
		],
	],

];
?>
