<?php
$projects["series"][] = [

    "title"       => "Tantamounts",
    "subtitle"    => "",
    "slug"        => "flat_mountains",
    "description" => "Mountains computationally reconfigured to a flat horizon.",
    "works"       => [
        [
            "id"          => "jkk_",
            "title"       => "Tantamount Everest",
            "slug"        => "",
            "medium"      => "",
            "date"        => "",
            "height"      => "",
            "width"       => "",
            "units"       => "",
            "offset"      => "210",
            "status"      => "",
        ],
        [
            "id"          => "jkk_",
            "title"       => "Tantamount St. Helens (CVO Photo Archive)",
            "slug"        => "",
            "medium"      => "",
            "date"        => "",
            "height"      => "",
            "width"       => "",
            "units"       => "",
            "offset"      => "126",
            "status"      => "",
        ],
        [
            "id"          => "jkk_",
            "title"       => "Tantamount Hadley",
            "slug"        => "",
            "medium"      => "",
            "date"        => "",
            "height"      => "",
            "width"       => "",
            "units"       => "",
            "offset"      => "193",
            "status"      => "",
        ],
        [
            "id"          => "jkk_",
            "title"       => "Tantamount Rushmore",
            "slug"        => "",
            "medium"      => "",
            "date"        => "",
            "height"      => "",
            "width"       => "",
            "units"       => "",
            "offset"      => "132",
            "status"      => "",
        ],
        [
            "id"          => "jkk_",
            "title"       => "Tantamount Fuji (U.S. Air Force)",
            "slug"        => "",
            "medium"      => "",
            "date"        => "",
            "height"      => "",
            "width"       => "",
            "units"       => "",
            "offset"      => "189",
            "status"      => "",
        ],
        [
            "id"          => "jkk_",
            "title"       => "Tantamount McKinley",
            "slug"        => "",
            "medium"      => "",
            "date"        => "",
            "height"      => "",
            "width"       => "",
            "units"       => "",
            "offset"      => "197",
            "status"      => "",
        ],
        [
            "id"          => "jkk_",
            "title"       => "Tantamount Rushmore",
            "slug"        => "",
            "medium"      => "",
            "date"        => "",
            "height"      => "",
            "width"       => "",
            "units"       => "",
            "offset"      => "175",
            "status"      => "",
        ],
        [
            "id"          => "jkk_",
            "title"       => "Tantamount Tetons (Ansel)",
            "slug"        => "",
            "medium"      => "",
            "date"        => "",
            "height"      => "",
            "width"       => "",
            "units"       => "",
            "offset"      => "198",
            "status"      => "",
        ],
        [
            "id"          => "jkk_",
            "title"       => "Tantamount K2",
            "slug"        => "",
            "medium"      => "",
            "date"        => "",
            "height"      => "",
            "width"       => "",
            "units"       => "",
            "offset"      => "25",
            "status"      => "",
        ],
        [
            "id"          => "jkk_",
            "title"       => "Tantamount Kilimanjaro",
            "slug"        => "",
            "medium"      => "",
            "date"        => "",
            "height"      => "",
            "width"       => "",
            "units"       => "",
            "offset"      => "169",
            "status"      => "",
        ],
        [
            "id"          => "jkk_",
            "title"       => "Tantamount Paramount 2008",
            "slug"        => "",
            "medium"      => "",
            "date"        => "",
            "height"      => "",
            "width"       => "",
            "units"       => "",
            "offset"      => "132",
            "status"      => "",
        ],
        [
            "id"          => "jkk_",
            "title"       => "Tantamount Everest",
            "slug"        => "",
            "medium"      => "",
            "date"        => "",
            "height"      => "",
            "width"       => "",
            "units"       => "",
            "offset"      => "200",
            "status"      => "",
        ],
        [
            "id"          => "jkk_",
            "title"       => "Tantamount Unknown",
            "slug"        => "",
            "medium"      => "",
            "date"        => "",
            "height"      => "",
            "width"       => "",
            "units"       => "",
            "offset"      => "142",
            "status"      => "",
        ],
        [
            "id"          => "jkk_",
            "title"       => "Tantamount Unknown",
            "slug"        => "",
            "medium"      => "",
            "date"        => "",
            "height"      => "",
            "width"       => "",
            "units"       => "",
            "offset"      => "155",
            "status"      => "",
        ],
        [
            "id"          => "jkk_",
            "title"       => "Tantamount Unknown",
            "slug"        => "",
            "medium"      => "",
            "date"        => "",
            "height"      => "",
            "width"       => "",
            "units"       => "",
            "offset"      => "135",
            "status"      => "",
        ],
        [
            "id"          => "jkk_",
            "title"       => "Tantamount Unknown",
            "slug"        => "",
            "medium"      => "",
            "date"        => "",
            "height"      => "",
            "width"       => "",
            "units"       => "",
            "offset"      => "93",
            "status"      => "",
        ],
        [
            "id"          => "jkk_",
            "title"       => "Tantamount Unknown",
            "slug"        => "",
            "medium"      => "",
            "date"        => "",
            "height"      => "",
            "width"       => "",
            "units"       => "",
            "offset"      => "233",
            "status"      => "",
        ],
        [
            "id"          => "jkk_",
            "title"       => "Tantamount Rushmore",
            "slug"        => "",
            "medium"      => "",
            "date"        => "",
            "height"      => "",
            "width"       => "",
            "units"       => "",
            "offset"      => "127",
            "status"      => "",
        ],
        [
            "id"          => "jkk_",
            "title"       => "Tantamount Saint Victoire Barnes",
            "slug"        => "",
            "medium"      => "",
            "date"        => "",
            "height"      => "",
            "width"       => "",
            "units"       => "",
            "offset"      => "194",
            "status"      => "",
        ],
        [
            "id"          => "jkk_",
            "title"       => "Tantamount Bryce",
            "slug"        => "",
            "medium"      => "",
            "date"        => "",
            "height"      => "",
            "width"       => "",
            "units"       => "",
            "offset"      => "196",
            "status"      => "",
        ],
        [
            "id"          => "jkk_",
            "title"       => "Tantamount Fuji (woodcut)",
            "slug"        => "",
            "medium"      => "",
            "date"        => "",
            "height"      => "",
            "width"       => "",
            "units"       => "",
            "offset"      => "217",
            "status"      => "",
        ],
        [
            "id"          => "jkk_",
            "title"       => "Tantamount Wild Wonders",
            "slug"        => "",
            "medium"      => "",
            "date"        => "",
            "height"      => "",
            "width"       => "",
            "units"       => "",
            "offset"      => "214",
            "status"      => "",
        ],
        [
            "id"          => "jkk_",
            "title"       => "Tantamount Rockies",
            "slug"        => "",
            "medium"      => "",
            "date"        => "",
            "height"      => "",
            "width"       => "",
            "units"       => "",
            "offset"      => "0",
            "status"      => "",
        ],
        [
            "id"          => "jkk_",
            "title"       => "Tantamount Fuji",
            "slug"        => "",
            "medium"      => "",
            "date"        => "",
            "height"      => "",
            "width"       => "",
            "units"       => "",
            "offset"      => "216",
            "status"      => "",
        ],
    ],

];
?>
