<?php
$projects["series"][] = [
	"title"       => "The Adaption to My Generation",
	"subtitle"    => "A daily photo project",
	"slug"        => "daily_photo",
	"description" => "<p>JK Keller takes a self-portrait every day for 17+ years (1998 October 1)</p>

		<p>Yes, I am still taking a photo every day.</p>

		<p>Next video: Oct 2022</p>",
	"works"     => [
		[
			"id"          => "jkk_",
			"title"       => "Frequently Asked Questions",
			"slug"        => "info_faqs",
			"description" => "Questions and comments JK’s received regarding his daily photo project.",
		],
		[
			"id"          => "jkk_",
			"title"       => "Related Photo Projects",
			"slug"        => "related_photo_projects",
			"description" => "Links to various photography projects related to JK Keller’s daily photo project.",
		],
		[
			"id"          => "jkk_",
			"title"       => "2018 Was a Mean Year",
			"slug"        => "average_jk_2018",
			"medium"      => "c-print",
			"date"        => "2018",
			"height"      => "",
			"width"       => "",
			"units"       => "",
			"description" => "The year 2018 in daily self portraits.",
		],
		[
			"id"          => "jkk_",
			"title"       => "2017 Was a Mean Year",
			"slug"        => "average_jk_2017",
			"medium"      => "c-print",
			"date"        => "2017",
			"height"      => "",
			"width"       => "",
			"units"       => "",
			"description" => "The year 2017 in daily self portraits.",
		],
		[
			"id"          => "jkk_",
			"title"       => "2016 Was a Mean Year",
			"slug"        => "average_jk_2016",
			"medium"      => "c-print",
			"date"        => "2016",
			"height"      => "",
			"width"       => "",
			"units"       => "",
			"description" => "The year 2016 in daily self portraits.",
		],
		[
			"id"          => "jkk_",
			"title"       => "2015 Was a Mean Year",
			"slug"        => "average_jk_2015",
			"medium"      => "c-print",
			"date"        => "2015",
			"height"      => "",
			"width"       => "",
			"units"       => "",
			"description" => "The year 2015 in daily self portraits.",
		],
		[
			"id"          => "jkk_",
			"title"       => "2014 Was a Mean Year",
			"slug"        => "average_jk_2014",
			"medium"      => "c-print",
			"date"        => "2014",
			"height"      => "",
			"width"       => "",
			"units"       => "",
			"description" => "The year 2014 in daily self portraits.",
		],
		[
			"id"          => "jkk_",
			"title"       => "Living My Life Faster, 2014",
			"slug"        => "living_my_life_faster_2014",
			"medium"      => "video",
			"date"        => "2014",
			"height"      => "",
			"width"       => "",
			"units"       => "",
			"description" => "JK Keller takes a daily self-portrait every day for 16 years and makes a timelapse video.",
		],
		[
			"id"          => "jkk_",
			"title"       => "2013 Was a Mean Year",
			"slug"        => "average_jk_2013",
			"medium"      => "c-print",
			"date"        => "2013",
			"height"      => "",
			"width"       => "",
			"units"       => "",
			"description" => "The year 2013 in daily self portraits.",
		],
		[
			"id"          => "jkk_",
			"title"       => "2012 Was a Mean Year",
			"slug"        => "average_jk_2012",
			"medium"      => "c-print",
			"date"        => "2012",
			"height"      => "",
			"width"       => "",
			"units"       => "",
			"description" => "The year 2012 in daily self portraits.",
		],
		[
			"id"          => "jkk_",
			"title"       => "2011 Was a Mean Year",
			"slug"        => "average_jk_2011",
			"medium"      => "c-print",
			"date"        => "2011",
			"height"      => "",
			"width"       => "",
			"units"       => "",
			"description" => "The year 2011 in daily self portraits.",
		],
		[
			"id"          => "jkk_",
			"title"       => "2010 Was a Mean Year",
			"slug"        => "average_jk_2010",
			"medium"      => "c-print",
			"date"        => "2010",
			"height"      => "",
			"width"       => "",
			"units"       => "",
			"description" => "The year 2010 in daily self portraits.",
		],
		[
			"id"          => "jkk_",
			"title"       => "2009 Was a Mean Year",
			"slug"        => "average_jk_2009",
			"medium"      => "c-print",
			"date"        => "2009",
			"height"      => "",
			"width"       => "",
			"units"       => "",
			"description" => "The year 2009 in daily self portraits.",
		],
		[
			"id"          => "jkk_",
			"title"       => "2008 Was a Mean Year",
			"slug"        => "average_jk_2008",
			"medium"      => "c-print",
			"date"        => "2008",
			"height"      => "",
			"width"       => "",
			"units"       => "",
			"description" => "The year 2008 in daily self portraits.",
		],
		[
			"id"          => "jkk_",
			"title"       => "2007 Was a Mean Year",
			"slug"        => "average_jk_2007",
			"medium"      => "c-print",
			"date"        => "2007",
			"height"      => "",
			"width"       => "",
			"units"       => "",
			"description" => "The year 2007 in daily self portraits.",
		],
		[
			"id"          => "jkk_",
			"title"       => "2006 Was a Mean Year",
			"slug"        => "average_jk_2006",
			"medium"      => "c-print",
			"date"        => "2006",
			"height"      => "",
			"width"       => "",
			"units"       => "",
			"description" => "The year 2006 in daily self portraits.",
		],
		[
			"id"          => "jkk_",
			"title"       => "Living My Life Faster, 2006",
			"slug"        => "living_my_life_faster_2006",
			"medium"      => "video",
			"date"        => "2006",
			"height"      => "",
			"width"       => "",
			"units"       => "",
			"description" => "JK Keller takes a daily self-portrait every day for 8 years and makes a timelapse video.",
		],
		[
			"id"          => "jkk_",
			"title"       => "2005 Was a Mean Year",
			"slug"        => "average_jk_2005",
			"medium"      => "c-print",
			"date"        => "2005",
			"height"      => "",
			"width"       => "",
			"units"       => "",
			"description" => "The year 2005 in daily self portraits.",
		],
		[
			"id"          => "jkk_",
			"title"       => "2004 Was a Mean Year",
			"slug"        => "average_jk_2004",
			"medium"      => "c-print",
			"date"        => "2004",
			"height"      => "",
			"width"       => "",
			"units"       => "",
			"description" => "The year 2004 in daily self portraits.",
		],
		[
			"id"          => "jkk_",
			"title"       => "2003 Was a Mean Year",
			"slug"        => "average_jk_2003",
			"medium"      => "c-print",
			"date"        => "2003",
			"height"      => "",
			"width"       => "",
			"units"       => "",
			"description" => "The year 2003 in daily self portraits.",
		],
		[
			"id"          => "jkk_",
			"title"       => "2002 Was a Mean Year",
			"slug"        => "average_jk_2002",
			"medium"      => "c-print",
			"date"        => "2002",
			"height"      => "",
			"width"       => "",
			"units"       => "",
			"description" => "The year 2002 in daily self portraits.",
		],
		[
			"id"          => "jkk_",
			"title"       => "2001 Was a Mean Year",
			"slug"        => "average_jk_2001",
			"medium"      => "c-print",
			"date"        => "2001",
			"height"      => "",
			"width"       => "",
			"units"       => "",
			"description" => "The year 2001 in daily self portraits.",
		],
		[
			"id"          => "jkk_",
			"title"       => "2000 Was a Mean Year",
			"slug"        => "average_jk_2000",
			"medium"      => "c-print",
			"date"        => "2000",
			"height"      => "",
			"width"       => "",
			"units"       => "",
			"description" => "The year 2000 in daily self portraits.",
		],
		[
			"id"          => "jkk_",
			"title"       => "1999 Was a Mean Year",
			"slug"        => "average_jk_1999",
			"medium"      => "c-print",
			"date"        => "1999",
			"height"      => "",
			"width"       => "",
			"units"       => "",
			"description" => "The year 1999 in daily self portraits.",
		],
		[
			"id"          => "jkk_",
			"title"       => "1998 Was a Mean Year",
			"slug"        => "average_jk_1998",
			"medium"      => "c-print",
			"date"        => "1998",
			"height"      => "",
			"width"       => "",
			"units"       => "",
			"description" => "The year 1998 in daily self portraits.",
		],
	],
];
?>
