<?php

$projects = [
	[
		'id'          => 'jkk_',
		'title'       => 'I Wanna Be a Single Lady Too',
		'slug'        => 'dance_puppets',
		'sort_date'   => '2016',
		'nice_date'   => '2015–2016',
		'description' => '',
		'status'      => '',
		'notes'       => '',
	],
	[
		'id'          => 'jkk_',
		'title'       => 'bASCIIats',
		'slug'        => 'ocr_compositions',
		'sort_date'   => '',
		'nice_date'   => '',
		'description' => '',
		'status'      => '',
		'notes'       => '',
	],
	[
		'slug'        => 'sd_to_hd',
		'series'      =>  true,
	],
	[
		'slug'        => 'touching_film',
		'series'      =>  true,
	],
	[
		'id'          => 'jkk_',
		'title'       => 'The Internet is a Series of Tube Socks',
		'slug'        => 'internet_tube_socks',
		'sort_date'   => '2013',
		'nice_date'   => '2013',
		'description' => '',
		'status'      => 'leftovers',
		'notes'       => '',
	],
	[
		'id'          => 'jkd_',
		'title'       => 'Museum as Manufacturer',
		'slug'        => '3d_model_maker',
		'sort_date'   => '2013',
		'nice_date'   => '2013',
		'description' => '',
		'byline'      => '',
		'status'      => '',
		'notes'       => 'collab with <a href="https://fromkeetra.com/museum-as-manufacturer/">Keetra Dean Dixon</a>',
	],
	[
		'id'          => 'jkd_201301_1',
		'title'       => 'Twice as Forever',
		'slug'        => 'burning_both_ends',
		'sort_date'   => '2013',
		'nice_date'   => '2013',
		'description' => '',
		'status'      => '',
		'notes'       => 'collaborative submission to Yule Log with <a href="https://fromkeetra.com/twice-as-forever/">Keetra Dean Dixon</a>',
	],
	[
		'slug'        => 'iphone_oil_paintings',
		'series'      =>  true,
	],
	[
		'id'          => 'jkd_201201_1',
		'title'       => 'Bear with me',
		'slug'        => 'glass_trailer_hitch',
		'sort_date'   => '2012',
		'nice_date'   => '2012',
		'description' => '',
		'status'      => '',
		'notes'       => 'collaborative work for GlassLab with <a href="https://fromkeetra.com/twice-as-forever/">Keetra Dean Dixon</a>',
	],
	[
		'id'          => 'jkk_',
		'title'       => 'I’ve Been LO0oOonging For You',
		'slug'        => 'penis_enlargement',
		'sort_date'   => '2012',
		'nice_date'   => '2012',
		'description' => '8==============D',
		'status'      => '',
		'notes'       => 'NSFW (<em>no really</em>)',
	],
	[
		'id'          => 'jkk_',
		'title'       => 'Realigning My Thoughts On Jasper Johns',
		'slug'        => 'unlignments/simpsons_realigned',
		'sort_date'   => '2011',
		'nice_date'   => '2011',
		'description' => 'Season 10, Episode 19, ’Mom and Pop Art’ of The Simpsons is processed through vectorization, various alignments, & audio manipulations.',
		'status'      => '',
		'notes'       => '',
	],
	[
		'id'          => 'jkk_',
		'title'       => 'Selections',
		'slug'        => 'edit_select_all',
		'sort_date'   => '',
		'nice_date'   => '',
		'description' => '',
		'status'      => '',
		'notes'       => '⌘-a/crtl-a: Select all',
	],
	[
		'id'          => 'jkk_',
		'title'       => '',
		'subtitle'    => 'Generative Prints',
		'slug'        => 'generative_prints',
		'sort_date'   => '',
		'nice_date'   => '',
		'description' => '',
		'status'      => '',
		'notes'       => '',
	],
	[
		'id'          => '',
		'title'       => 'Unfortunate Wikipedia Banner Pairings',
		'slug'        => 'wikipedia_banner_pairings',
		'description' => 'Wikipedia asks for donations and gets unexpected humor.',
		'sort_date'   => '2010',
		'nice_date'   => '2010',
		'status'      => '',
		'notes'       => '',
	],
	[
		'id'          => 'jkk_',
		'title'       => 'Attempting to Draw a Straight Line on a Scanner',
		'slug'        => 'scanner_lines',
		'sort_date'   => '2010',
		'nice_date'   => '2010',
		'description' => '',
		'status'      => '',
		'notes'       => '',
	],
	[
		'slug'        => 'arrow_iterations',
		'series'      =>  true,
	],
	[
		'id'          => 'jkd_201009_1',
		'title'       => 'Embrace the Amazing Mistake',
		'slug'        => 'doublespeak/amazing_mistake',
		'description' => '',
		'medium'      => 'offset print',
		'sort_date'   => '2010_09_01',
		'nice_date'   => '2010',
		'height'      =>  22,
		'width'       =>  17,
		'units'       => 'in',
		'status'      => '<a href="https://fromjtok.bigcartel.com/product/amazing-mistake">Available</a>',
		'notes'       => 'collaborative commission for GOOD magazine with <a href="https://fromkeetra.com/amazing-mistake/">Keetra Dean Dixon</a>',
		'imgfile'     => '',
	],
	[
		'id'          => '',
		'title'       => 'Hand Harp',
		'slug'        => 'hand_harp',
		'description' => '',
		'sort_date'   => '2009',
		'nice_date'   => '2009?',
		'status'      => '',
		'notes'       => 'for Google symphony?',
	],
	[
		'id'          => '',
		'title'       => 'Quips',
		'slug'        => 'fan_letter_q',
		'description' => 'A fan letter to the letter Q',
		'sort_date'   => '2009',
		'nice_date'   => '2009?',
		'status'      => '',
		'notes'       => 'for PostTypography event',
	],
	[
		'published'   =>  true,
		'slug'        => 'dots_dots_dots',
		'series'      =>  true,
	],
	[
		'slug'        => 'siri_sound_poems',
		'series'      =>  true,
	],
	[
		'slug'        => 'fucking_windows',
		'series'      =>  true,
	],
	[
		'id'          => '',
		'title'       => 'Counting the Movies I’ve Seen',
		'slug'        => 'counting_movies',
		'description' => '',
		'sort_date'   => '2009',
		'nice_date'   => '2009',
		'status'      => '',
		'notes'       => '1–25',
	],
	[
		'slug'        => 'profiles_exchanged',
		'series'      =>  true,
	],
	[
		'slug'        => 'profiles_reversed',
		'series'      =>  true,
	],
	[
		'id'          => '',
		'title'       => 'VHS Box Characters',
		'slug'        => 'vhs_box_characters',
		'description' => '',
		'sort_date'   => '2008',
		'nice_date'   => '2008?',
		'status'      => '',
		'notes'       => 'for Tokion (I wish I were better at illustration)',
	],
	[
		'id'          => 'jkk_',
		'title'       => 'Songs About Rainbows',
		'slug'        => 'rainbow_folders',
		'sort_date'   => '2008',
		'nice_date'   => '2008',
		'description' => 'Application that colors your OS X folders.',
		'status'      => '',
		'notes'       => '',
	],
	[
		'published'   =>  true,
		'slug'        => 'flat_mountains',
		'series'      =>  true,
	],
	[
		'slug'        => 'layered_wax',
		'series'      =>  true,
	],
	[
		'id'          => '',
		'title'       => '25$ Minimum Order?',
		'slug'        => 'minimum_shapeways_order',
		'description' => 'Purchasing the minimum of the minimum 3d prints',
		'sort_date'   => '2007',
		'nice_date'   => '2007?',
		'status'      => 'to photograph',
		'notes'       => '',
	],
	[
		'id'          => '',
		'title'       => 'Getting Rid of Cranbrook',
		'subtitle'    => 'Before & After',
		'slug'        => 'before_after_haircut',
		'description' => '',
		'sort_date'   => '2007',
		'nice_date'   => '2007',
		'status'      => '',
		'notes'       => 'unofficially used in Mexican shaving banner ad, “Make a Difference” poster, and “Faces of Meth” video.',
	],
	[
		'id'          => '',
		'title'       => 'A Fictitious Argument Emerges Between Coriolis & Beaufort',
		'slug'        => 'fans_flags',
		'description' => 'Fans & Flags',
		'sort_date'   => '2007',
		'nice_date'   => '2007',
		'status'      => '',
		'notes'       => '',
	],
	[
		'id'          => 'jkk_',
		'title'       => 'Domestic Spacial Turbulence',
		'slug'        => 'spinning_house',
		'sort_date'   => '2007',
		'nice_date'   => '2007',
		'description' => '',
		'status'      => '',
		'notes'       => '',
	],
	[
		'id'          => '',
		'title'       => 'Tequiladega Nights Poster',
		'slug'        => 'tequiladega_nights_poster',
		'description' => '',
		'sort_date'   => '2007',
		'nice_date'   => '2007',
		'status'      => '',
		'notes'       => '',
	],
	[
		'id'          => '',
		'title'       => 'Mail Pillow',
		'slug'        => 'mail_pillow',
		'description' => '',
		'sort_date'   => '2007',
		'nice_date'   => '2007',
		'status'      => '',
		'notes'       => '',
	],
	[
		'id'          => '',
		'title'       => 'A Case Study in favor of Global Warming',
		'slug'        => 'new_years_2007_cards',
		'description' => 'New Year’s card for 2007',
		'sort_date'   => '2007',
		'nice_date'   => '2007',
		'status'      => '',
		'notes'       => '',
	],
	[
		'id'          => '',
		'title'       => 'Two Non-Fiction Moments',
		'slug'        => 'non_fiction_photos',
		'description' => '',
		'sort_date'   => '2007',
		'nice_date'   => '2007',
		'status'      => '',
		'notes'       => 'True found situations',
	],
	[
		'id'          => '',
		'title'       => 'How to Photograph a Design Poster',
		'slug'        => 'poster_holder',
		'description' => '',
		'sort_date'   => '2006',
		'nice_date'   => '2006',
		'status'      => '',
		'notes'       => '',
	],
	[
		'id'          => 'jkk_',
		'title'       => 'Insecurity Envelopes',
		'slug'        => 'laser_cut_envelopes',
		'sort_date'   => '2006',
		'nice_date'   => '2006',
		'description' => 'Laser_cut envelopes',
		'status'      => '',
		'notes'       => '',
	],
	[
		'id'          => 'jkk_',
		'title'       => 'Signifficient',
		'subtitle'    => 'a type generator',
		'slug'        => 'scaling_limits_type_generator',
		'sort_date'   => '',
		'nice_date'   => '2006',
		'description' => 'Type created by reaching Illustrator’s mathematical limitations',
		'status'      => '',
		'notes'       => '',
	],
	[
		'id'          => 'jkk_',
		'title'       => 'I will ALWAYS believe in WORK ',
		'slug'        => 'believe_in_work_poster',
		'sort_date'   => '2006',
		'nice_date'   => '',
		'description' => '',
		'status'      => '',
		'notes'       => 'from PostBitScriptMapper',
	],
	[
		'id'          => 'jkk_',
		'title'       => 'Spamstractions',
		'slug'        => 'spam_abstractions',
		'sort_date'   => '2006',
		'nice_date'   => '2006',
		'description' => 'Abstract art created from spam images.',
		'status'      => '',
		'notes'       => '',
	],
	[
		'id'          => 'jkk_',
		'title'       => 'Unlignments',
		'slug'        => 'clip_art_alignments',
		'sort_date'   => '2006',
		'nice_date'   => '',
		'description' => '',
		'status'      => 'remember when I was gonna create a <a href="https://twitter.com/unlignments">bot</a>?',
		'notes'       => '',
		'pages'   => [
			[
				'title'       => 'Breathing Buildings',
				'slug'        => 'breathing_buildings',
			],
			[
				'title'       => 'Upside Frowns',
				'slug'        => 'upside_frowns',
			],
			[
				'title'       => 'Realigning Thoughts',
				'slug'        => 'realigning _thoughts',
			],
			[
				'title'       => 'Others (gifs, etc.)',
				'slug'        => 'various',
			],
		],
	],
	[
		'id'          => '',
		'title'       => 'Paulette (folded) Typeface',
		'slug'        => 'folded_ribbon_type',
		'description' => 'Typeface created by folding ribbon',
		'sort_date'   => '2006',
		'nice_date'   => '2006',
		'status'      => '',
		'notes'       => '',
	],
	[
		'id'          => '',
		'title'       => '',
		'subtitle'    => 'Harmen Liemburg Lecture Poster',
		'slug'        => 'harmen_liemburg_poster',
		'description' => '',
		'sort_date'   => '2006',
		'nice_date'   => '2006',
		'status'      => '',
		'notes'       => '',
	],
	[
		'id'          => '',
		'title'       => 'Justifiably Me',
		'slug'        => 'justifiably_me',
		'description' => 'not all ASCII is created equal',
		'sort_date'   => '2006',
		'nice_date'   => '2006',
		'status'      => '',
		'notes'       => '',
	],
	[
		'id'          => '',
		'title'       => '',
		'subtitle'    => 'Business Card & Postcard',
		'slug'        => 'letterpress_spam_cards',
		'description' => '',
		'sort_date'   => '2006',
		'nice_date'   => '2006',
		'status'      => '',
		'notes'       => 'Inspired by Japanese spam',
	],
	[
		'id'          => '',
		'title'       => 'Live Free or Die',
		'slug'        => 'fence_type',
		'description' => 'ribbon, fence, type',
		'sort_date'   => '2006',
		'nice_date'   => '2006',
		'status'      => '',
		'notes'       => '<em>well, that’s embarrassing</em>',
	],
	[
		'id'          => 'jkk_200609_2',
		'title'       => 'Jumper Bumpers',
		'slug'        => 'jumper_bumpers',
		'description' => 'Intro bumpers for Cranbrook 2D Design students',
		'medium'      => 'offset print',
		'duration'    => '1:16 min',
		'sort_date'   => '2006_09_02',
		'nice_date'   => '2006',
		'status'      => '',
		'notes'       => '',
		'embed'       => '<style>.figure-embed { width: 100%; max-width: 640px; max-height: 100vh; } .embed-container { position: relative; padding-bottom: 75%; height: 0; overflow: hidden; max-width: 100%; } .embed-container iframe, .embed-container object, .embed-container embed { position: absolute; top: 0; left: 0; width: 100%; height: 100%; max-height: 90vh; }</style><div class="figure-embed"><div class="embed-container"><iframe src="https://player.vimeo.com/video/412158703" frameborder="0" webkitAllowFullScreen mozallowfullscreen allowFullScreen></iframe></div></div>',
	],
	[
		'id'          => 'jkk_',
		'title'       => 'Slitscan',
		'subtitle'    => 'a type generator',
		'slug'        => 'slitscan_type_generator',
		'sort_date'   => '2006 & 2009',
		'nice_date'   => '2006 & 2009',
		'description' => 'Letterforms are generated from users’ font collections.',
		'status'      => '',
		'notes'       => '',
	],
	[
		'id'          => '',
		'title'       => 'I Heart You',
		'slug'        => 'timeshift_video',
		'description' => '',
		'sort_date'   => '2005',
		'nice_date'   => '2005',
		'status'      => '',
		'notes'       => 'before I found out this was basically an After Effects plugin',
	],
	[
		'id'          => 'jkk_',
		'title'       => 'Fingerspelling Matchbooks',
		'slug'        => 'fingerspelling_matchbooks',
		'sort_date'   => '2005',
		'nice_date'   => '2005',
		'description' => 'Matches in found matchbooks are bent to look like hands.',
		'status'      => '',
		'notes'       => 'American Sign Language +',
	],
	[
		'slug'        => 'dirty_mousepads',
		'series'      =>  true,
	],
	[
		'id'          => 'jkk_',
		'title'       => 'PostBitScriptMapper',
		'subtitle'    => 'a type generator',
		'slug'        => 'bitmap_to_vector_type_generator',
		'sort_date'   => '2005',
		'nice_date'   => '2005',
		'description' => 'Type generator attempting to turn bitmap fonts into vector typefaces.',
		'status'      => '',
		'notes'       => '',
	],
	[
		'id'          => 'jkk_',
		'title'       => 'Hero Shirt: Princess Peach',
		'slug'        => 'princess_peach_shirt',
		'sort_date'   => '2005',
		'nice_date'   => '2005',
		'description' => '',
		'status'      => '',
		'notes'       => 'collab with my mom',
	],
	[
		'id'          => 'jkk_',
		'title'       => 'Volumetric Redundancies',
		'slug'        => 'word_visualizer',
		'sort_date'   => '2001',
		'nice_date'   => '2001',
		'description' => 'Visualizing the structure and word usage in a given text.',
		'status'      => '',
		'notes'       => '',
	],
	[
		'id'          => 'jkk_',
		'title'       => 'www.from',
		'subtitle'    => 'Where We Went From',
		'slug'        => 'web_visualizer',
		'sort_date'   => '2001–2006',
		'nice_date'   => '2001–2006',
		'description' => 'Visualizing the interconnected nature of websites.',
		'status'      => '',
		'notes'       => '',
	],
	[
		'id'          => 'jkk_',
		'title'       => 'Informal Inquiries',
		'slug'        => 'informal_inquiries',
		'sort_date'   => '',
		'nice_date'   => '',
		'description' => '',
		'status'      => '',
		'notes'       => '',
		'pages'   => [
			[
				'title'       => 'x.coms',
				'slug'        => 'x_coms',
			],
			[
				'title'       => 'Rhizome Submissions',
				'slug'        => 'rhizome',
			],
			[
				'title'       => 'Moires',
				'slug'        => 'resizing',
			],
		],
	],
	[
		'published'   =>  true,
		'slug'        => 'boxbots',
		'series'      =>  true,
	],
	[
		'published'   =>  true,
		'slug'        => 'daily_photo',
		'series'      =>  true,
	],
	[
		'slug'        => 'homepages',
		'series'      =>  true,
	],
	[
		'slug'        => 'drawings',
		'series'      =>  true,
	],
	[
		'id'          => 'jkk_',
		'title'       => '',
		'subtitle'    => 'Various scripting',
		'slug'        => 'scripts',
		'sort_date'   => '',
		'nice_date'   => '',
		'description' => '',
		'status'      => '',
		'notes'       => 'Wellderly, etc.',
	],

];
