<?php

$series_boxbot_submissions = [
	'slug'        => 'boxbots/submissions',
	'js'          => NULL,
	'title'       => 'BoxBot Submissions',
	'nice_date'   => '',
	'status'      => 'Accepting Submissions',
//
// SEE AT BOTTOM - SEE AT BOTTOM - SEE AT BOTTOM - SEE AT BOTTOM - SEE AT BOTTOM - SEE AT BOTTOM
	'description' => '',
// SEE AT BOTTOM - SEE AT BOTTOM - SEE AT BOTTOM - SEE AT BOTTOM - SEE AT BOTTOM - SEE AT BOTTOM
//
	'notes'       => '',
	'meta_description'    => 'Bot characters made from altered product packaging, submitted from around the world',
	'twitter_image'       => 'https://jk-keller.com/o__o/boxbots/submissions/x__x/jk_keller-boxbots-submissions-shadow-1024x512.png',
	'open_graph_image'    => 'https://jk-keller.com/o__o/boxbots/submissions/x__x/jk_keller-boxbots-submissions-color-1200x630.png',

];

$collection_boxbot_submissions = [
	// 'extends' => '_layouts.boxbot',
	'extends' => [
		'color' => '_layouts.color-sub',
		'shadow' => '_layouts.shadow-sub',
	],
	// 'path' => 'o__o/{collection}/{slug}',
	'path' => [
		'color' => 'o__o/boxbots/{collection}/{slug}',
		'shadow' => 'o__o/boxbots/{collection}/shadow/{slug}',
	],
	'sort' => '-id',

	'series_info'         => $series_boxbot_submissions,
	'twitter_card_type'   => 'summary',

	'items' => [
		[
			'id'                  => '1999_12_28-michelle-001',
			'title'               => 'Chivas Regal',
			'person'              => 'Michelle',
			'slug'                => '1999_12_28-michelle-001',
			'sort_date'           => '1999_12_28',
			'nice_date'           => '1999 Dec 28',
			'medium'              => 'altered found packaging',
			'location'            => 'Antarctica',
			'imgfile'             => '1999_12_28-michelle-001',
			'small_height_px'     => 150,
			'small_width_px'      => 106,
			'large_height_px'     => 600,
			'large_width_px'      => 424,
		],
		[
			'id'                  => '2003_02_14-kaylene-001',
			'title'               => '',
			'nontitle'            => 'Untitled',
			'person'              => 'Kaylene',
			'slug'                => '2003_02_14-kaylene-001',
			'sort_date'           => '2003_02_14',
			'nice_date'           => '2003 Feb 14',
			'medium'              => 'altered found packaging',
			'location'            => 'email',
			'imgfile'             => '2003_02_14-kaylene-001',
			'small_height_px'     => 150,
			'small_width_px'      => 104,
			'large_height_px'     => 230,
			'large_width_px'      => 160,
		],
		[
			'id'                  => '2003_07_09-taikou-001',
			'title'               => '',
			'nontitle'            => 'Untitled',
			'person'              => 'Taikou',
			'slug'                => '2003_07_09-taikou-001',
			'sort_date'           => '2003_07_09',
			'nice_date'           => '2003 Jul 09',
			'medium'              => 'altered found packaging',
			'location'            => 'email',
			'imgfile'             => '2003_07_09-taikou-001',
			'small_height_px'     => 150,
			'small_width_px'      => 149,
			'large_height_px'     => 250,
			'large_width_px'      => 248,
		],
		[
			'id'                  => '2003_08_14-mub-001',
			'title'               => '',
			'nontitle'            => 'Untitled',
			'person'              => 'Mub',
			'slug'                => '2003_08_14-mub-001',
			'sort_date'           => '2003_08_14',
			'nice_date'           => '2003 Aug 14',
			'medium'              => 'altered found packaging',
			'location'            => 'email',
			'imgfile'             => '2003_08_14-mub-001',
			'small_height_px'     => 150,
			'small_width_px'      => 111,
			'large_height_px'     => 260,
			'large_width_px'      => 192,
		],
		[
			'id'                  => '2004_01_20-aika-001',
			'title'               => '',
			'nontitle'            => 'Untitled',
			'person'              => 'Aika',
			'slug'                => '2004_01_20-aika-001',
			'sort_date'           => '2004_01_20',
			'nice_date'           => '2004 Jan 20',
			'medium'              => 'altered found packaging',
			'location'            => 'email',
			'imgfile'             => '2004_01_20-aika-001',
			'small_height_px'     => 150,
			'small_width_px'      => 125,
			'large_height_px'     => 510,
			'large_width_px'      => 425,
		],
		[
			'id'                  => '2004_01_20-aika-002',
			'title'               => '',
			'nontitle'            => 'Untitled',
			'person'              => 'Aika',
			'slug'                => '2004_01_20-aika-002',
			'sort_date'           => '2004_01_20',
			'nice_date'           => '2004 Jan 20',
			'medium'              => 'altered found packaging',
			'location'            => 'email',
			'imgfile'             => '2004_01_20-aika-002',
			'small_height_px'     => 150,
			'small_width_px'      => 101,
			'large_height_px'     => 600,
			'large_width_px'      => 405,
		],
		[
			'id'                  => '2004_01_20-aika-003',
			'title'               => '',
			'nontitle'            => 'Untitled',
			'person'              => 'Aika',
			'slug'                => '2004_01_20-aika-003',
			'sort_date'           => '2004_01_20',
			'nice_date'           => '2004 Jan 20',
			'medium'              => 'altered found packaging',
			'location'            => 'email',
			'imgfile'             => '2004_01_20-aika-003',
			'small_height_px'     => 132,
			'small_width_px'      => 150,
			'large_height_px'     => 477,
			'large_width_px'      => 539,
		],
		[
			'id'                  => '2004_01_20-aika-004',
			'title'               => '',
			'nontitle'            => 'Untitled',
			'person'              => 'Aika',
			'slug'                => '2004_01_20-aika-004',
			'sort_date'           => '2004_01_20',
			'nice_date'           => '2004 Jan 20',
			'medium'              => 'altered found packaging',
			'location'            => 'email',
			'imgfile'             => '2004_01_20-aika-004',
			'small_height_px'     => 150,
			'small_width_px'      => 122,
			'large_height_px'     => 420,
			'large_width_px'      => 341,
		],
		[
			'id'                  => '2004_01_20-aika-005',
			'title'               => '',
			'nontitle'            => 'Untitled',
			'person'              => 'Aika',
			'slug'                => '2004_01_20-aika-005',
			'sort_date'           => '2004_01_20',
			'nice_date'           => '2004 Jan 20',
			'medium'              => 'altered found packaging',
			'location'            => 'email',
			'imgfile'             => '2004_01_20-aika-005',
			'small_height_px'     => 150,
			'small_width_px'      => 102,
			'large_height_px'     => 487,
			'large_width_px'      => 332,
		],
		[
			'id'                  => '2004_01_21-aika-006',
			'title'               => '',
			'nontitle'            => 'Untitled',
			'person'              => 'Aika',
			'slug'                => '2004_01_21-aika-006',
			'sort_date'           => '2004_01_21',
			'nice_date'           => '2004 Jan 21',
			'medium'              => 'altered found packaging',
			'location'            => 'email',
			'imgfile'             => '2004_01_21-aika-006',
			'small_height_px'     => 150,
			'small_width_px'      => 128,
			'large_height_px'     => 381,
			'large_width_px'      => 327,
		],
		[
			'id'                  => '2004_01_21-aika-007',
			'title'               => '',
			'nontitle'            => 'Untitled',
			'person'              => 'Aika',
			'slug'                => '2004_01_21-aika-007',
			'sort_date'           => '2004_01_21',
			'nice_date'           => '2004 Jan 21',
			'medium'              => 'altered found packaging',
			'location'            => 'email',
			'imgfile'             => '2004_01_21-aika-007',
			'small_height_px'     => 150,
			'small_width_px'      => 128,
			'large_height_px'     => 600,
			'large_width_px'      => 514,
		],
		[
			'id'                  => '2004_03_10-jesse-001',
			'title'               => '',
			'nontitle'            => 'Untitled',
			'person'              => 'Jesse',
			'slug'                => '2004_03_10-jesse-001',
			'sort_date'           => '2004_03_10',
			'nice_date'           => '2004 Mar 10',
			'medium'              => 'altered found packaging',
			'location'            => 'email',
			'imgfile'             => '2004_03_10-jesse-001',
			'small_height_px'     => 150,
			'small_width_px'      => 134,
			'large_height_px'     => 600,
			'large_width_px'      => 538,
		],
		[
			'id'                  => '2004_04_28-irene-001',
			'title'               => '',
			'nontitle'            => 'Untitled',
			'person'              => 'Irene',
			'slug'                => '2004_04_28-irene-001',
			'sort_date'           => '2004_04_28',
			'nice_date'           => '2004 Apr 28',
			'medium'              => 'altered found packaging',
			'location'            => 'email',
			'imgfile'             => '2004_04_28-irene-001',
			'small_height_px'     => 150,
			'small_width_px'      => 103,
			'large_height_px'     => 600,
			'large_width_px'      => 413,
		],
		[
			'id'                  => '2004_07_03-ivan-001',
			'title'               => '',
			'nontitle'            => 'Untitled',
			'person'              => 'Ivan',
			'slug'                => '2004_07_03-ivan-001',
			'sort_date'           => '2004_07_03',
			'nice_date'           => '2004 Jul 03',
			'medium'              => 'altered found packaging',
			'location'            => 'email',
			'imgfile'             => '2004_07_03-ivan-001',
			'small_height_px'     => 150,
			'small_width_px'      => 94,
			'large_height_px'     => 384,
			'large_width_px'      => 242,
		],
		[
			'id'                  => '2004_07_03-karen-001',
			'title'               => '',
			'nontitle'            => 'Untitled',
			'person'              => 'Karen',
			'slug'                => '2004_07_03-karen-001',
			'sort_date'           => '2004_07_03',
			'nice_date'           => '2004 Jul 03',
			'medium'              => 'altered found packaging',
			'location'            => 'email',
			'imgfile'             => '2004_07_03-karen-001',
			'small_height_px'     => 150,
			'small_width_px'      => 135,
			'large_height_px'     => 297,
			'large_width_px'      => 269,
		],
		[
			'id'                  => '2004_12_20-esteban-001',
			'title'               => '',
			'nontitle'            => 'Untitled',
			'person'              => 'Esteban',
			'slug'                => '2004_12_20-esteban-001',
			'sort_date'           => '2004_12_20',
			'nice_date'           => '2004 Dec 20',
			'medium'              => 'altered found packaging',
			'location'            => 'email',
			'imgfile'             => '2004_12_20-esteban-001',
			'small_height_px'     => 145,
			'small_width_px'      => 150,
			'large_height_px'     => 484,
			'large_width_px'      => 499,
		],
		[
			'id'                  => '2004_12_20-esteban-002',
			'title'               => '',
			'nontitle'            => 'Untitled',
			'person'              => 'Esteban',
			'slug'                => '2004_12_20-esteban-002',
			'sort_date'           => '2004_12_20',
			'nice_date'           => '2004 Dec 20',
			'medium'              => 'altered found packaging',
			'location'            => 'email',
			'imgfile'             => '2004_12_20-esteban-002',
			'small_height_px'     => 150,
			'small_width_px'      => 113,
			'large_height_px'     => 489,
			'large_width_px'      => 370,
		],
		[
			'id'                  => '2004_12_20-esteban-003',
			'title'               => '',
			'nontitle'            => 'Untitled',
			'person'              => 'Esteban',
			'slug'                => '2004_12_20-esteban-003',
			'sort_date'           => '2004_12_20',
			'nice_date'           => '2004 Dec 20',
			'medium'              => 'altered found packaging',
			'location'            => 'email',
			'imgfile'             => '2004_12_20-esteban-003',
			'small_height_px'     => 150,
			'small_width_px'      => 134,
			'large_height_px'     => 488,
			'large_width_px'      => 437,
		],
		[
			'id'                  => '2005_04_26-akim-001',
			'title'               => '',
			'nontitle'            => 'Untitled',
			'person'              => 'Akim',
			'slug'                => '2005_04_26-akim-001',
			'sort_date'           => '2005_04_26',
			'nice_date'           => '2005 Apr 26',
			'medium'              => 'altered found packaging',
			'location'            => 'email',
			'imgfile'             => '2005_04_26-akim-001',
			'small_height_px'     => 150,
			'small_width_px'      => 78,
			'large_height_px'     => 600,
			'large_width_px'      => 313,
		],
		[
			'id'                  => '2005_04_26-andrea-001',
			'title'               => '',
			'nontitle'            => 'Untitled',
			'person'              => 'Andrea',
			'slug'                => '2005_04_26-andrea-001',
			'sort_date'           => '2005_04_26',
			'nice_date'           => '2005 Apr 26',
			'medium'              => 'altered found packaging',
			'location'            => 'email',
			'imgfile'             => '2005_04_26-andrea-001',
			'small_height_px'     => 150,
			'small_width_px'      => 120,
			'large_height_px'     => 485,
			'large_width_px'      => 389,
		],
		[
			'id'                  => '2005_04_26-cheng-001',
			'title'               => '',
			'nontitle'            => 'Untitled',
			'person'              => 'Cheng',
			'slug'                => '2005_04_26-cheng-001',
			'sort_date'           => '2005_04_26',
			'nice_date'           => '2005 Apr 26',
			'medium'              => 'altered found packaging',
			'location'            => 'email',
			'imgfile'             => '2005_04_26-cheng-001',
			'small_height_px'     => 150,
			'small_width_px'      => 114,
			'large_height_px'     => 600,
			'large_width_px'      => 457,
		],
		[
			'id'                  => '2005_04_26-daniel-001',
			'title'               => '',
			'nontitle'            => 'Untitled',
			'person'              => 'Daniel',
			'slug'                => '2005_04_26-daniel-001',
			'sort_date'           => '2005_04_26',
			'nice_date'           => '2005 Apr 26',
			'medium'              => 'altered found packaging',
			'location'            => 'email',
			'imgfile'             => '2005_04_26-daniel-001',
			'small_height_px'     => 150,
			'small_width_px'      => 116,
			'large_height_px'     => 516,
			'large_width_px'      => 400,
		],
		[
			'id'                  => '2005_04_26-daniel-002',
			'title'               => '',
			'nontitle'            => 'Untitled',
			'person'              => 'Daniel',
			'slug'                => '2005_04_26-daniel-002',
			'sort_date'           => '2005_04_26',
			'nice_date'           => '2005 Apr 26',
			'medium'              => 'altered found packaging',
			'location'            => 'email',
			'imgfile'             => '2005_04_26-daniel-002',
			'small_height_px'     => 150,
			'small_width_px'      => 117,
			'large_height_px'     => 516,
			'large_width_px'      => 405,
		],
		[
			'id'                  => '2005_04_26-fadime-001',
			'title'               => '',
			'nontitle'            => 'Untitled',
			'person'              => 'Fadime',
			'slug'                => '2005_04_26-fadime-001',
			'sort_date'           => '2005_04_26',
			'nice_date'           => '2005 Apr 26',
			'medium'              => 'altered found packaging',
			'location'            => 'email',
			'imgfile'             => '2005_04_26-fadime-001',
			'small_height_px'     => 150,
			'small_width_px'      => 137,
			'large_height_px'     => 600,
			'large_width_px'      => 548,
		],
		[
			'id'                  => '2005_04_26-haris-001',
			'title'               => '',
			'nontitle'            => 'Untitled',
			'person'              => 'Haris',
			'slug'                => '2005_04_26-haris-001',
			'sort_date'           => '2005_04_26',
			'nice_date'           => '2005 Apr 26',
			'medium'              => 'altered found packaging',
			'location'            => 'email',
			'imgfile'             => '2005_04_26-haris-001',
			'small_height_px'     => 150,
			'small_width_px'      => 129,
			'large_height_px'     => 479,
			'large_width_px'      => 413,
		],
		[
			'id'                  => '2005_04_26-ing-001',
			'title'               => '',
			'nontitle'            => 'Untitled',
			'person'              => 'Ing',
			'slug'                => '2005_04_26-ing-001',
			'sort_date'           => '2005_04_26',
			'nice_date'           => '2005 Apr 26',
			'medium'              => 'altered found packaging',
			'location'            => 'email',
			'imgfile'             => '2005_04_26-ing-001',
			'small_height_px'     => 150,
			'small_width_px'      => 112,
			'large_height_px'     => 600,
			'large_width_px'      => 450,
		],
		[
			'id'                  => '2005_04_26-janine-001',
			'title'               => '',
			'nontitle'            => 'Untitled',
			'person'              => 'Janine',
			'slug'                => '2005_04_26-janine-001',
			'sort_date'           => '2005_04_26',
			'nice_date'           => '2005 Apr 26',
			'medium'              => 'altered found packaging',
			'location'            => 'email',
			'imgfile'             => '2005_04_26-janine-001',
			'small_height_px'     => 150,
			'small_width_px'      => 119,
			'large_height_px'     => 600,
			'large_width_px'      => 477,
		],
		[
			'id'                  => '2005_04_26-janine-002',
			'title'               => '',
			'nontitle'            => 'Untitled',
			'person'              => 'Janine',
			'slug'                => '2005_04_26-janine-002',
			'sort_date'           => '2005_04_26',
			'nice_date'           => '2005 Apr 26',
			'medium'              => 'altered found packaging',
			'location'            => 'email',
			'imgfile'             => '2005_04_26-janine-002',
			'small_height_px'     => 150,
			'small_width_px'      => 116,
			'large_height_px'     => 598,
			'large_width_px'      => 465,
		],
		[
			'id'                  => '2005_05_05-eva-001',
			'title'               => 'HIGH NOON',
			'person'              => 'Eva',
			'slug'                => '2005_05_05-eva-001',
			'sort_date'           => '2005_05_05',
			'nice_date'           => '2005 May 05',
			'medium'              => 'altered found packaging',
			'location'            => 'email',
			'imgfile'             => '2005_05_05-eva-001',
			'small_height_px'     => 150,
			'small_width_px'      => 106,
			'large_height_px'     => 600,
			'large_width_px'      => 424,
		],
		[
			'id'                  => '2005_05_05-eva-002',
			'title'               => 'GHOST',
			'person'              => 'Eva',
			'slug'                => '2005_05_05-eva-002',
			'sort_date'           => '2005_05_05',
			'nice_date'           => '2005 May 05',
			'medium'              => 'altered found packaging',
			'location'            => 'email',
			'imgfile'             => '2005_05_05-eva-002',
			'small_height_px'     => 150,
			'small_width_px'      => 106,
			'large_height_px'     => 600,
			'large_width_px'      => 424,
		],
		[
			'id'                  => '2007_04_12-denis',
			'title'               => '',
			'nontitle'            => 'Untitled',
			'person'              => 'Denis',
			'slug'                => '2007_04_12-denis',
			'sort_date'           => '2007_04_12',
			'nice_date'           => '2007 Apr 12',
			'medium'              => 'altered found packaging',
			'location'            => 'email',
			'imgfile'             => '2007_04_12-denis',
			'small_height_px'     => 150,
			'small_width_px'      => 96,
			'large_height_px'     => 300,
			'large_width_px'      => 193,
		],
		[
			'id'                  => '2007_04_12-diana',
			'title'               => '',
			'nontitle'            => 'Untitled',
			'person'              => 'Diana',
			'slug'                => '2007_04_12-diana',
			'sort_date'           => '2007_04_12',
			'nice_date'           => '2007 Apr 12',
			'medium'              => 'altered found packaging',
			'location'            => 'email',
			'imgfile'             => '2007_04_12-diana',
			'small_height_px'     => 148,
			'small_width_px'      => 150,
			'large_height_px'     => 295,
			'large_width_px'      => 300,
		],
		[
			'id'                  => '2007_04_12-marie_therese',
			'title'               => '',
			'nontitle'            => 'Untitled',
			'person'              => 'Marie Therese',
			'slug'                => '2007_04_12-marie_therese',
			'sort_date'           => '2007_04_12',
			'nice_date'           => '2007 Apr 12',
			'medium'              => 'altered found packaging',
			'location'            => 'email',
			'imgfile'             => '2007_04_12-marie_therese',
			'small_height_px'     => 150,
			'small_width_px'      => 90,
			'large_height_px'     => 300,
			'large_width_px'      => 181,
		],
		[
			'id'                  => '2007_04_12-marina',
			'title'               => '',
			'nontitle'            => 'Untitled',
			'person'              => 'Marina',
			'slug'                => '2007_04_12-marina',
			'sort_date'           => '2007_04_12',
			'nice_date'           => '2007 Apr 12',
			'medium'              => 'altered found packaging',
			'location'            => 'email',
			'imgfile'             => '2007_04_12-marina',
			'small_height_px'     => 150,
			'small_width_px'      => 115,
			'large_height_px'     => 300,
			'large_width_px'      => 231,
		],
		[
			'id'                  => '2007_04_12-markus',
			'title'               => 'Nougatmann',
			'person'              => 'Markus',
			'slug'                => '2007_04_12-markus',
			'sort_date'           => '2007_04_12',
			'nice_date'           => '2007 Apr 12',
			'medium'              => 'altered found packaging',
			'location'            => 'email',
			'imgfile'             => '2007_04_12-markus',
			'small_height_px'     => 150,
			'small_width_px'      => 110,
			'large_height_px'     => 300,
			'large_width_px'      => 219,
		],
		[
			'id'                  => '2007_04_12-melanie',
			'title'               => '',
			'nontitle'            => 'Untitled',
			'person'              => 'Melanie',
			'slug'                => '2007_04_12-melanie',
			'sort_date'           => '2007_04_12',
			'nice_date'           => '2007 Apr 12',
			'medium'              => 'altered found packaging',
			'location'            => 'email',
			'imgfile'             => '2007_04_12-melanie',
			'small_height_px'     => 150,
			'small_width_px'      => 126,
			'large_height_px'     => 300,
			'large_width_px'      => 252,
		],
		[
			'id'                  => '2007_04_12-melli',
			'title'               => '',
			'nontitle'            => 'Untitled',
			'person'              => 'Melli',
			'slug'                => '2007_04_12-melli',
			'sort_date'           => '2007_04_12',
			'nice_date'           => '2007 Apr 12',
			'medium'              => 'altered found packaging',
			'location'            => 'email',
			'imgfile'             => '2007_04_12-melli',
			'small_height_px'     => 150,
			'small_width_px'      => 92,
			'large_height_px'     => 300,
			'large_width_px'      => 184,
		],
		[
			'id'                  => '2007_04_12-natalie',
			'title'               => '',
			'nontitle'            => 'Untitled',
			'person'              => 'Natalie',
			'slug'                => '2007_04_12-natalie',
			'sort_date'           => '2007_04_12',
			'nice_date'           => '2007 Apr 12',
			'medium'              => 'altered found packaging',
			'location'            => 'email',
			'imgfile'             => '2007_04_12-natalie',
			'small_height_px'     => 150,
			'small_width_px'      => 113,
			'large_height_px'     => 300,
			'large_width_px'      => 226,
		],
		[
			'id'                  => '2007_04_12-nathalie',
			'title'               => '',
			'nontitle'            => 'Untitled',
			'person'              => 'Nathalie',
			'slug'                => '2007_04_12-nathalie',
			'sort_date'           => '2007_04_12',
			'nice_date'           => '2007 Apr 12',
			'medium'              => 'altered found packaging',
			'location'            => 'email',
			'imgfile'             => '2007_04_12-nathalie',
			'small_height_px'     => 150,
			'small_width_px'      => 121,
			'large_height_px'     => 300,
			'large_width_px'      => 241,
		],
		[
			'id'                  => '2007_04_12-nathi',
			'title'               => '',
			'nontitle'            => 'Untitled',
			'person'              => 'Nathi',
			'slug'                => '2007_04_12-nathi',
			'sort_date'           => '2007_04_12',
			'nice_date'           => '2007 Apr 12',
			'medium'              => 'altered found packaging',
			'location'            => 'email',
			'imgfile'             => '2007_04_12-nathi',
			'small_height_px'     => 150,
			'small_width_px'      => 136,
			'large_height_px'     => 300,
			'large_width_px'      => 273,
		],
		[
			'id'                  => '2007_04_12-nina',
			'title'               => '',
			'nontitle'            => 'Untitled',
			'person'              => 'Nina',
			'slug'                => '2007_04_12-nina',
			'sort_date'           => '2007_04_12',
			'nice_date'           => '2007 Apr 12',
			'medium'              => 'altered found packaging',
			'location'            => 'email',
			'imgfile'             => '2007_04_12-nina',
			'small_height_px'     => 150,
			'small_width_px'      => 108,
			'large_height_px'     => 300,
			'large_width_px'      => 217,
		],
		[
			'id'                  => '2007_04_12-rabia',
			'title'               => '',
			'nontitle'            => 'Untitled',
			'person'              => 'Rabia',
			'slug'                => '2007_04_12-rabia',
			'sort_date'           => '2007_04_12',
			'nice_date'           => '2007 Apr 12',
			'medium'              => 'altered found packaging',
			'location'            => 'email',
			'imgfile'             => '2007_04_12-rabia',
			'small_height_px'     => 150,
			'small_width_px'      => 135,
			'large_height_px'     => 300,
			'large_width_px'      => 270,
		],
		[
			'id'                  => '2007_04_12-rika',
			'title'               => '',
			'nontitle'            => 'Untitled',
			'person'              => 'Rika',
			'slug'                => '2007_04_12-rika',
			'sort_date'           => '2007_04_12',
			'nice_date'           => '2007 Apr 12',
			'medium'              => 'altered found packaging',
			'location'            => 'email',
			'imgfile'             => '2007_04_12-rika',
			'small_height_px'     => 150,
			'small_width_px'      => 101,
			'large_height_px'     => 300,
			'large_width_px'      => 203,
		],
		[
			'id'                  => '2007_04_12-suzana',
			'title'               => '',
			'nontitle'            => 'Untitled',
			'person'              => 'Suzana',
			'slug'                => '2007_04_12-suzana',
			'sort_date'           => '2007_04_12',
			'nice_date'           => '2007 Apr 12',
			'medium'              => 'altered found packaging',
			'location'            => 'email',
			'imgfile'             => '2007_04_12-suzana',
			'small_height_px'     => 150,
			'small_width_px'      => 99,
			'large_height_px'     => 300,
			'large_width_px'      => 199,
		],
		[
			'id'                  => '2007_04_12-tamara',
			'title'               => '',
			'nontitle'            => 'Untitled',
			'person'              => 'Tamara',
			'slug'                => '2007_04_12-tamara',
			'sort_date'           => '2007_04_12',
			'nice_date'           => '2007 Apr 12',
			'medium'              => 'altered found packaging',
			'location'            => 'email',
			'imgfile'             => '2007_04_12-tamara',
			'small_height_px'     => 150,
			'small_width_px'      => 86,
			'large_height_px'     => 300,
			'large_width_px'      => 172,
		],
		[
			'id'                  => '2008_04_14-maya',
			'title'               => '',
			'nontitle'            => 'Untitled',
			'person'              => 'Maya',
			'slug'                => '2008_04_14-maya',
			'sort_date'           => '2008_04_14',
			'nice_date'           => '2008 Apr 14',
			'medium'              => 'altered found packaging',
			'location'            => 'email',
			'imgfile'             => '2008_04_14-maya',
			'small_height_px'     => 139,
			'small_width_px'      => 150,
			'large_height_px'     => 147,
			'large_width_px'      => 158,
		],
		[
			'id'                  => '2009_03_09-bagus-001',
			'title'               => '',
			'nontitle'            => 'Untitled',
			'person'              => 'Bagus',
			'slug'                => '2009_03_09-bagus-001',
			'sort_date'           => '2009_03_09',
			'nice_date'           => '2009 Mar 09',
			'medium'              => 'altered found packaging',
			'location'            => 'email',
			'imgfile'             => '2009_03_09-bagus-001',
			'small_height_px'     => 148,
			'small_width_px'      => 150,
			'large_height_px'     => 542,
			'large_width_px'      => 550,
		],
		[
			'id'                  => '2005_04_26-ing-002',
			'title'               => '',
			'nontitle'            => 'Untitled',
			'person'              => 'Ing',
			'slug'                => '2005_04_26-ing-002',
			'sort_date'           => '2005_04_26',
			'nice_date'           => '2005 Apr 26',
			'medium'              => 'altered found packaging',
			'location'            => 'email',
			'imgfile'             => '2005_04_26-ing-002',
			'small_height_px'     => 150,
			'small_width_px'      => 112,
			'large_height_px'     => 600,
			'large_width_px'      => 450,
		],
		[
			'id'                  => '2005_04_26-kathi-001',
			'title'               => '',
			'nontitle'            => 'Untitled',
			'person'              => 'Kathi',
			'slug'                => '2005_04_26-kathi-001',
			'sort_date'           => '2005_04_26',
			'nice_date'           => '2005 Apr 26',
			'medium'              => 'altered found packaging',
			'location'            => 'email',
			'imgfile'             => '2005_04_26-kathi-001',
			'small_height_px'     => 150,
			'small_width_px'      => 118,
			'large_height_px'     => 600,
			'large_width_px'      => 472,
		],
		[
			'id'                  => '2005_04_26-lisa-001',
			'title'               => '',
			'nontitle'            => 'Untitled',
			'person'              => 'Lisa',
			'slug'                => '2005_04_26-lisa-001',
			'sort_date'           => '2005_04_26',
			'nice_date'           => '2005 Apr 26',
			'medium'              => 'altered found packaging',
			'location'            => 'email',
			'imgfile'             => '2005_04_26-lisa-001',
			'small_height_px'     => 150,
			'small_width_px'      => 106,
			'large_height_px'     => 600,
			'large_width_px'      => 424,
		],
		[
			'id'                  => '2005_04_26-lukas-001',
			'title'               => '',
			'nontitle'            => 'Untitled',
			'person'              => 'Lukas',
			'slug'                => '2005_04_26-lukas-001',
			'sort_date'           => '2005_04_26',
			'nice_date'           => '2005 Apr 26',
			'medium'              => 'altered found packaging',
			'location'            => 'email',
			'imgfile'             => '2005_04_26-lukas-001',
			'small_height_px'     => 150,
			'small_width_px'      => 65,
			'large_height_px'     => 600,
			'large_width_px'      => 262,
		],
		[
			'id'                  => '2005_04_26-maja-001',
			'title'               => '',
			'nontitle'            => 'Untitled',
			'person'              => 'Maja',
			'slug'                => '2005_04_26-maja-001',
			'sort_date'           => '2005_04_26',
			'nice_date'           => '2005 Apr 26',
			'medium'              => 'altered found packaging',
			'location'            => 'email',
			'imgfile'             => '2005_04_26-maja-001',
			'small_height_px'     => 150,
			'small_width_px'      => 118,
			'large_height_px'     => 600,
			'large_width_px'      => 474,
		],
		[
			'id'                  => '2005_04_26-marco-001',
			'title'               => '',
			'nontitle'            => 'Untitled',
			'person'              => 'Marco',
			'slug'                => '2005_04_26-marco-001',
			'sort_date'           => '2005_04_26',
			'nice_date'           => '2005 Apr 26',
			'medium'              => 'altered found packaging',
			'location'            => 'email',
			'imgfile'             => '2005_04_26-marco-001',
			'small_height_px'     => 150,
			'small_width_px'      => 111,
			'large_height_px'     => 600,
			'large_width_px'      => 445,
		],
		[
			'id'                  => '2005_04_26-marina-001',
			'title'               => '',
			'nontitle'            => 'Untitled',
			'person'              => 'Marina',
			'slug'                => '2005_04_26-marina-001',
			'sort_date'           => '2005_04_26',
			'nice_date'           => '2005 Apr 26',
			'medium'              => 'altered found packaging',
			'location'            => 'email',
			'imgfile'             => '2005_04_26-marina-001',
			'small_height_px'     => 112,
			'small_width_px'      => 150,
			'large_height_px'     => 449,
			'large_width_px'      => 600,
		],
		[
			'id'                  => '2005_04_26-markus-001',
			'title'               => '',
			'nontitle'            => 'Untitled',
			'person'              => 'Markus',
			'slug'                => '2005_04_26-markus-001',
			'sort_date'           => '2005_04_26',
			'nice_date'           => '2005 Apr 26',
			'medium'              => 'altered found packaging',
			'location'            => 'email',
			'imgfile'             => '2005_04_26-markus-001',
			'small_height_px'     => 110,
			'small_width_px'      => 150,
			'large_height_px'     => 441,
			'large_width_px'      => 600,
		],
		[
			'id'                  => '2005_04_26-markus-002',
			'title'               => '',
			'nontitle'            => 'Untitled',
			'person'              => 'Markus',
			'slug'                => '2005_04_26-markus-002',
			'sort_date'           => '2005_04_26',
			'nice_date'           => '2005 Apr 26',
			'medium'              => 'altered found packaging',
			'location'            => 'email',
			'imgfile'             => '2005_04_26-markus-002',
			'small_height_px'     => 150,
			'small_width_px'      => 106,
			'large_height_px'     => 600,
			'large_width_px'      => 425,
		],
		[
			'id'                  => '2005_04_26-solmaz-001',
			'title'               => '',
			'nontitle'            => 'Untitled',
			'person'              => 'Solmaz',
			'slug'                => '2005_04_26-solmaz-001',
			'sort_date'           => '2005_04_26',
			'nice_date'           => '2005 Apr 26',
			'medium'              => 'altered found packaging',
			'location'            => 'email',
			'imgfile'             => '2005_04_26-solmaz-001',
			'small_height_px'     => 150,
			'small_width_px'      => 112,
			'large_height_px'     => 600,
			'large_width_px'      => 450,
		],
		[
			'id'                  => '2007_04_12-hanna',
			'title'               => '',
			'nontitle'            => 'Untitled',
			'person'              => 'Hanna',
			'slug'                => '2007_04_12-hanna',
			'sort_date'           => '2007_04_12',
			'nice_date'           => '2007 Apr 12',
			'medium'              => 'altered found packaging',
			'location'            => 'email',
			'imgfile'             => '2007_04_12-hanna',
			'small_height_px'     => 110,
			'small_width_px'      => 150,
			'large_height_px'     => 221,
			'large_width_px'      => 300,
		],
	],
];

$series_boxbot_submissions['description'] = 'People have submitted '.count($collection_boxbot_submissions['items']).' of their own <a href="/o__o/boxbots/">BoxBot</a> creations. Send me an email with yours! jk at jk-keller dot com';

