<?php

$series_daily_photo = [
	'slug'        => 'daily_photo',
	'js'          => null,
	'title'       => 'The Adaption to My Generation',
	'subtitle'    => 'A daily photo project',
	'nice_date'   => '1998 Oct 01–until I’m not',
	'status'      => 'Yes, I am still taking a photo every day.',
	'description' => '<p>JK Keller takes a self-portrait every day for 21+ years (1998 October 1)</p>
		<p>Next video: Nov 2022</p>',
	'notes'       => '',
	'to_dos'      => '',
	'hidden'      => '',
	'prj_nice_date'   => '1998–death',
	'prj_status'      => 'ongoing',
	'prj_description' => 'Older and Older',
	'prj_notes'       => 'Next video: 2022',
];

$collection_daily_photo = [
	'extends' => '_layouts.single-daily_photo',
	'path'    => 'o__o/{collection}/{slug}',
	'sort'    => '-id',
	'items'   => [
		[
			'id'          => 'page-1',
			'title'       => 'Frequently Asked Questions',
			'slug'        => 'info_faqs',
			'notes'       => 'Questions and comments JK’s received regarding his daily photo project.',
		],
		[
			'id'              => 'page-2',
			'title'           => 'Related Photo Projects',
			'slug'        => 'related_photo_projects',
			'notes'       => 'Links to various photography projects related to JK Keller’s daily photo project.',
		],
		[
			'id'                  => 'jkk_202001_1',
			'title'               => '2019 Was a Mean Year',
			'slug'                => 'average_jk_2019',
			'medium'              => 'c-print',
			'location'            => 'digital',
			'sort_date'           => '2020_01_01',
			'nice_date'           => '2020 Jan 01',
			'imgfile'             => 'jk_keller-202001_1-average_jk_2019.jpg',
			'height'              => 128,
			'width'               => 96,
			'small_height_px'     => 128*1.5,
			'small_width_px'      => 96*1.5,
			'large_height_px'     => 1280/2,
			'large_width_px'      => 960/2,
			'units'               => 'mm',
			'description'         => 'The year 2019 in daily self portraits.',
		],
		[
			'id'                  => 'jkk_201901_1',
			'title'               => '2018 Was a Mean Year',
			'slug'                => 'average_jk_2018',
			'medium'              => 'c-print',
			'location'            => 'digital',
			'sort_date'           => '2019_01_01',
			'nice_date'           => '2019 Jan 01',
			'imgfile'             => 'jk_keller-201901_1-average_jk_2018.jpg',
			'height'              => 128,
			'width'               => 96,
			'small_height_px'     => 128*1.5,
			'small_width_px'      => 96*1.5,
			'large_height_px'     => 1280/2,
			'large_width_px'      => 960/2,
			'units'               => 'mm',
			'description'         => 'The year 2018 in daily self portraits.',
		],
		[
			'id'                  => 'jkk_201801_1',
			'title'               => '2017 Was a Mean Year',
			'slug'                => 'average_jk_2017',
			'medium'              => 'c-print',
			'location'            => 'digital',
			'sort_date'           => '2018_01_01',
			'nice_date'           => '2018 Jan 01',
			'imgfile'             => 'jk_keller-201801_1-average_jk_2017.jpg',
			'height'              => 128,
			'width'               => 96,
			'small_height_px'     => 128*1.5,
			'small_width_px'      => 96*1.5,
			'large_height_px'     => 1280/2,
			'large_width_px'      => 960/2,
			'units'               => 'mm',
			'description'         => 'The year 2017 in daily self portraits.',
		],
		[
			'id'                  => 'jkk_201701_1',
			'title'               => '2016 Was a Mean Year',
			'slug'                => 'average_jk_2016',
			'medium'              => 'c-print',
			'location'            => 'digital',
			'sort_date'           => '2017_01_01',
			'nice_date'           => '2017 Jan 01',
			'imgfile'             => 'jk_keller-201701_1-average_jk_2016.jpg',
			'height'              => 128,
			'width'               => 96,
			'small_height_px'     => 128*1.5,
			'small_width_px'      => 96*1.5,
			'large_height_px'     => 1280/2,
			'large_width_px'      => 960/2,
			'units'               => 'mm',
			'description'         => 'The year 2016 in daily self portraits.',
		],
		[
			'id'                  => 'jkk_201601_1',
			'title'               => '2015 Was a Mean Year',
			'slug'                => 'average_jk_2015',
			'medium'              => 'c-print',
			'location'            => 'digital',
			'sort_date'           => '2016_01_01',
			'nice_date'           => '2016 Jan 01',
			'imgfile'             => 'jk_keller-201601_1-average_jk_2015.jpg',
			'height'              => 128,
			'width'               => 96,
			'small_height_px'     => 128*1.5,
			'small_width_px'      => 96*1.5,
			'large_height_px'     => 1280/2,
			'large_width_px'      => 960/2,
			'units'               => 'mm',
			'description'         => 'The year 2015 in daily self portraits.',
		],
		[
			'id'                  => 'jkk_201501_1',
			'title'               => '2014 Was a Mean Year',
			'slug'                => 'average_jk_2014',
			'medium'              => 'c-print',
			'location'            => 'digital',
			'sort_date'           => '2015_01_01',
			'nice_date'           => '2015 Jan 01',
			'imgfile'             => 'jk_keller-201501_1-average_jk_2014.jpg',
			'height'              => 128,
			'width'               => 96,
			'small_height_px'     => 128*1.5,
			'small_width_px'      => 96*1.5,
			'large_height_px'     => 1280/2,
			'large_width_px'      => 960/2,
			'units'               => 'mm',
			'description'         => 'The year 2014 in daily self portraits.',
		],
		[
			'id'                  => 'jkk_201411_3',
			'title'               => 'Living My Life Faster, 2014',
			'slug'                => 'living_my_life_faster_2014',
			'medium'              => 'video',
			'location'            => 'digital',
			'sort_date'           => '2014_11_01',
			'nice_date'           => '2014 Nov 01',
			'imgfile'             => 'jk_keller-201411_3-living_my_life_faster_2014.png',
			'height'              => 128,
			'width'               => 96,
			'small_height_px'     => 128*1.5,
			'small_width_px'      => 96*1.5,
			'large_height_px'     => 1280/2,
			'large_width_px'      => 960/2,
			'units'               => 'mm',
			'description' => 'JK Keller takes a daily self-portrait every day for 16 years and makes a timelapse video.',
		],
		[
			'id'                  => 'jkk_201411_2',
			'title'               => 'Average JK, 1998–2014',
			'slug'                => 'average_jk_1998_2014',
			'medium'              => 'c-print',
			'location'            => 'digital',
			'sort_date'           => '2014_11_01',
			'nice_date'           => '2014 Nov 01',
			'imgfile'             => 'jk_keller-201411_2-average_jk_1998_2014.jpg',
			'height'              => 128,
			'width'               => 96,
			'small_height_px'     => 128*1.5,
			'small_width_px'      => 96*1.5,
			'large_height_px'     => 1280/2,
			'large_width_px'      => 960/2,
			'units'               => 'mm',
			'description' => '',
		],
		[
			'id'                  => 'jkk_201411_1',
			'title'               => 'Average JK, 2006–2014',
			'slug'                => 'average_jk_2006_2014',
			'medium'              => 'c-print',
			'location'            => 'digital',
			'sort_date'           => '2014_11_01',
			'nice_date'           => '2014 Nov 01',
			'imgfile'             => 'jk_keller-201411_1-average_jk_2006_2014.jpg',
			'height'              => 128,
			'width'               => 96,
			'small_height_px'     => 128*1.5,
			'small_width_px'      => 96*1.5,
			'large_height_px'     => 1280/2,
			'large_width_px'      => 960/2,
			'units'               => 'mm',
			'description' => '',
		],
		[
			'id'                  => 'jkk_201401_1',
			'title'               => '2013 Was a Mean Year',
			'slug'                => 'average_jk_2013',
			'medium'              => 'c-print',
			'location'            => 'digital',
			'sort_date'           => '2014_01_01',
			'nice_date'           => '2014 Jan 01',
			'imgfile'             => 'jk_keller-201401_1-average_jk_2013.jpg',
			'height'              => 128,
			'width'               => 96,
			'small_height_px'     => 128*1.5,
			'small_width_px'      => 96*1.5,
			'large_height_px'     => 1280/2,
			'large_width_px'      => 960/2,
			'units'               => 'mm',
			'description'         => 'The year 2013 in daily self portraits.',
		],
		[
			'id'                  => 'jkk_201301_1',
			'title'               => '2012 Was a Mean Year',
			'slug'                => 'average_jk_2012',
			'medium'              => 'c-print',
			'location'            => 'digital',
			'sort_date'           => '2013_01_01',
			'nice_date'           => '2013 Jan 01',
			'imgfile'             => 'jk_keller-201301_1-average_jk_2012.jpg',
			'height'              => 128,
			'width'               => 96,
			'small_height_px'     => 128*1.5,
			'small_width_px'      => 96*1.5,
			'large_height_px'     => 1280/2,
			'large_width_px'      => 960/2,
			'units'               => 'mm',
			'description'         => 'The year 2012 in daily self portraits.',
		],
		[
			'id'                  => 'jkk_201201_1',
			'title'               => '2011 Was a Mean Year',
			'slug'                => 'average_jk_2011',
			'medium'              => 'c-print',
			'location'            => 'digital',
			'sort_date'           => '2012_01_01',
			'nice_date'           => '2012 Jan 01',
			'imgfile'             => 'jk_keller-201201_1-average_jk_2011.jpg',
			'height'              => 128,
			'width'               => 96,
			'small_height_px'     => 128*1.5,
			'small_width_px'      => 96*1.5,
			'large_height_px'     => 1280/2,
			'large_width_px'      => 960/2,
			'units'               => 'mm',
			'description'         => 'The year 2011 in daily self portraits.',
		],
		[
			'id'                  => 'jkk_201101_1',
			'title'               => '2010 Was a Mean Year',
			'slug'                => 'average_jk_2010',
			'medium'              => 'c-print',
			'location'            => 'digital',
			'sort_date'           => '2011_01_01',
			'nice_date'           => '2011 Jan 01',
			'imgfile'             => 'jk_keller-201101_1-average_jk_2010.jpg',
			'height'              => 128,
			'width'               => 96,
			'small_height_px'     => 128*1.5,
			'small_width_px'      => 96*1.5,
			'large_height_px'     => 1280/2,
			'large_width_px'      => 960/2,
			'units'               => 'mm',
			'description'         => 'The year 2010 in daily self portraits.',
		],
		[
			'id'                  => 'jkk_201001_1',
			'title'               => '2009 Was a Mean Year',
			'slug'                => 'average_jk_2009',
			'medium'              => 'c-print',
			'location'            => 'digital',
			'sort_date'           => '2010_01_01',
			'nice_date'           => '2010 Jan 01',
			'imgfile'             => 'jk_keller-201001_1-average_jk_2009.jpg',
			'height'              => 128,
			'width'               => 96,
			'small_height_px'     => 128*1.5,
			'small_width_px'      => 96*1.5,
			'large_height_px'     => 1280/2,
			'large_width_px'      => 960/2,
			'units'               => 'mm',
			'description'         => 'The year 2009 in daily self portraits.',
		],
		[
			'id'                  => 'jkk_200901_1',
			'title'               => '2008 Was a Mean Year',
			'slug'                => 'average_jk_2008',
			'medium'              => 'c-print',
			'location'            => 'digital',
			'sort_date'           => '2009_01_01',
			'nice_date'           => '2009 Jan 01',
			'imgfile'             => 'jk_keller-200901_1-average_jk_2008.jpg',
			'height'              => 128,
			'width'               => 96,
			'small_height_px'     => 128*1.5,
			'small_width_px'      => 96*1.5,
			'large_height_px'     => 1280/2,
			'large_width_px'      => 960/2,
			'units'               => 'mm',
			'description'         => 'The year 2008 in daily self portraits.',
		],
		[
			'id'                  => 'jkk_200801_1',
			'title'               => '2007 Was a Mean Year',
			'slug'                => 'average_jk_2007',
			'medium'              => 'c-print',
			'location'            => 'digital',
			'sort_date'           => '2008_01_01',
			'nice_date'           => '2008 Jan 01',
			'imgfile'             => 'jk_keller-200801_1-average_jk_2007.jpg',
			'height'              => 128,
			'width'               => 96,
			'small_height_px'     => 128*1.5,
			'small_width_px'      => 96*1.5,
			'large_height_px'     => 1280/2,
			'large_width_px'      => 960/2,
			'units'               => 'mm',
			'description'         => 'The year 2007 in daily self portraits.',
		],
		[
			'id'                  => 'jkk_200701_1',
			'title'               => '2006 Was a Mean Year',
			'slug'                => 'average_jk_2006',
			'medium'              => 'c-print',
			'location'            => 'digital',
			'sort_date'           => '2007_01_01',
			'nice_date'           => '2007 Jan 01',
			'imgfile'             => 'jk_keller-200701_1-average_jk_2006.jpg',
			'height'              => 128,
			'width'               => 96,
			'small_height_px'     => 128*1.5,
			'small_width_px'      => 96*1.5,
			'large_height_px'     => 1280/2,
			'large_width_px'      => 960/2,
			'units'               => 'mm',
			'description'         => 'The year 2006 in daily self portraits.',
		],
		[
			'id'                  => 'jkk_200611_2',
			'title'               => 'Living My Life Faster, 2006',
			'slug'                => 'living_my_life_faster_2006',
			'medium'              => 'video',
			'location'            => 'digital',
			'sort_date'           => '2006_11_01',
			'nice_date'           => '2006 Nov 01',
			'imgfile'             => 'jk_keller-200611_2-living_my_life_faster_2006.png',
			'height'              => 128,
			'width'               => 96,
			'small_height_px'     => 128*1.5,
			'small_width_px'      => 96*1.5,
			'large_height_px'     => 1280/2,
			'large_width_px'      => 960/2,
			'units'               => 'mm',
			'embed'               => '<iframe src="https://player.vimeo.com/video/397812585" width="640" height="480" frameborder="0" allow="autoplay; fullscreen" allowfullscreen></iframe>',
			'description' => 'JK Keller takes a daily self-portrait every day for 8 years and makes a timelapse video.',
		],
		[
			'id'                  => 'jkk_200611_1',
			'title'               => 'Average JK, 1998–2006',
			'slug'                => 'average_jk_1998_2006',
			'medium'              => 'c-print',
			'location'            => 'digital',
			'sort_date'           => '2006_11_01',
			'nice_date'           => '2006 Nov 01',
			'imgfile'             => 'jk_keller-200611_1-average_jk_1998_2006.jpg',
			'height'              => 128,
			'width'               => 96,
			'small_height_px'     => 128*1.5,
			'small_width_px'      => 96*1.5,
			'large_height_px'     => 1280/2,
			'large_width_px'      => 960/2,
			'units'               => 'mm',
			'description' => '',
		],
		[
			'id'                  => 'jkk_200601_1',
			'title'               => '2005 Was a Mean Year',
			'slug'                => 'average_jk_2005',
			'medium'              => 'c-print',
			'location'            => 'digital',
			'sort_date'           => '2006_01_01',
			'nice_date'           => '2006 Jan 01',
			'imgfile'             => 'jk_keller-200601_1-average_jk_2005.jpg',
			'height'              => 128,
			'width'               => 96,
			'small_height_px'     => 128*1.5,
			'small_width_px'      => 96*1.5,
			'large_height_px'     => 1280/2,
			'large_width_px'      => 960/2,
			'units'               => 'mm',
			'description'         => 'The year 2005 in daily self portraits.',
		],
		[
			'id'                  => 'jkk_200501_1',
			'title'               => '2004 Was a Mean Year',
			'slug'                => 'average_jk_2004',
			'medium'              => 'c-print',
			'location'            => 'digital',
			'sort_date'           => '2005_01_01',
			'nice_date'           => '2005 Jan 01',
			'imgfile'             => 'jk_keller-200501_1-average_jk_2004.jpg',
			'height'              => 128,
			'width'               => 96,
			'small_height_px'     => 128*1.5,
			'small_width_px'      => 96*1.5,
			'large_height_px'     => 1280/2,
			'large_width_px'      => 960/2,
			'units'               => 'mm',
			'description'         => 'The year 2004 in daily self portraits.',
		],
		[
			'id'                  => 'jkk_200401_1',
			'title'               => '2003 Was a Mean Year',
			'slug'                => 'average_jk_2003',
			'medium'              => 'c-print',
			'location'            => 'digital',
			'sort_date'           => '2004_01_01',
			'nice_date'           => '2004 Jan 01',
			'imgfile'             => 'jk_keller-200401_1-average_jk_2003.jpg',
			'height'              => 128,
			'width'               => 96,
			'small_height_px'     => 128*1.5,
			'small_width_px'      => 96*1.5,
			'large_height_px'     => 1280/2,
			'large_width_px'      => 960/2,
			'units'               => 'mm',
			'description'         => 'The year 2003 in daily self portraits.',
		],
		[
			'id'                  => 'jkk_200301_1',
			'title'               => '2002 Was a Mean Year',
			'slug'                => 'average_jk_2002',
			'medium'              => 'c-print',
			'location'            => 'digital',
			'sort_date'           => '2003_01_01',
			'nice_date'           => '2003 Jan 01',
			'imgfile'             => 'jk_keller-200301_1-average_jk_2002.jpg',
			'height'              => 128,
			'width'               => 96,
			'small_height_px'     => 128*1.5,
			'small_width_px'      => 96*1.5,
			'large_height_px'     => 1280/2,
			'large_width_px'      => 960/2,
			'units'               => 'mm',
			'description'         => 'The year 2002 in daily self portraits.',
		],
		[
			'id'                  => 'jkk_200201_1',
			'title'               => '2001 Was a Mean Year',
			'slug'                => 'average_jk_2001',
			'medium'              => 'c-print',
			'location'            => 'digital',
			'sort_date'           => '2002_01_01',
			'nice_date'           => '2002 Jan 01',
			'imgfile'             => 'jk_keller-200201_1-average_jk_2001.jpg',
			'height'              => 128,
			'width'               => 96,
			'small_height_px'     => 128*1.5,
			'small_width_px'      => 96*1.5,
			'large_height_px'     => 1280/2,
			'large_width_px'      => 960/2,
			'units'               => 'mm',
			'description'         => 'The year 2001 in daily self portraits.',
		],
		[
			'id'                  => 'jkk_200101_1',
			'title'               => '2000 Was a Mean Year',
			'slug'                => 'average_jk_2000',
			'medium'              => 'c-print',
			'location'            => 'digital',
			'sort_date'           => '2001_01_01',
			'nice_date'           => '2001 Jan 01',
			'imgfile'             => 'jk_keller-200101_1-average_jk_2000.jpg',
			'height'              => 128,
			'width'               => 96,
			'small_height_px'     => 128*1.5,
			'small_width_px'      => 96*1.5,
			'large_height_px'     => 1280/2,
			'large_width_px'      => 960/2,
			'units'               => 'mm',
			'description'         => 'The year 2000 in daily self portraits.',
		],
		[
			'id'                  => 'jkk_200001_1',
			'title'               => '1999 Was a Mean Year',
			'slug'                => 'average_jk_1999',
			'medium'              => 'c-print',
			'location'            => 'digital',
			'sort_date'           => '2000_01_01',
			'nice_date'           => '2000 Jan 01',
			'imgfile'             => 'jk_keller-200001_1-average_jk_1999.jpg',
			'height'              => 128,
			'width'               => 96,
			'small_height_px'     => 128*1.5,
			'small_width_px'      => 96*1.5,
			'large_height_px'     => 1280/2,
			'large_width_px'      => 960/2,
			'units'               => 'mm',
			'description'         => 'The year 1999 in daily self portraits.',
		],
		[
			'id'                  => 'jkk_199901_1',
			'title'               => '1998 Was a Mean Year',
			'slug'                => 'average_jk_1998',
			'medium'              => 'c-print',
			'location'            => 'digital',
			'sort_date'           => '1999_01_01',
			'nice_date'           => '1999 Jan 01',
			'imgfile'             => 'jk_keller-199901_1-average_jk_1998.jpg',
			'height'              => 128,
			'width'               => 96,
			'small_height_px'     => 128*1.5,
			'small_width_px'      => 96*1.5,
			'large_height_px'     => 1280/2,
			'large_width_px'      => 960/2,
			'units'               => 'mm',
			'description'         => 'The year 1998 in daily self portraits.',
		],
	],
];
