<?php

$series_dirty_mousepads = [
	'slug'        => 'dirty_mousepads',
	'js'          => null,
	'title'       => 'Echoes',
	'subtitle'    => '',
	'nice_date'   => '2005+',
	'status'      => '',
	'hidden'      => '',
	'description' => '<p>By switching a typical mousepad with a sheet of paper, I am able to collect an echo of my computer use over the course of a few months. The resulting drawing embodies the filth one accumulates through prolonged use of technology.</p>',
	'notes'       => '',
	'to_dos'      => '<ul>
		<li>Rescan all so shadow edge all around?</li>
		<li>color correction action for scans?</li>
		<li>shoot photos of all (compare to scans)</li>
		<li>fix frames</li>
		<li>shoot photos of framed ones</li>
		<li>get more plastic sleeves & sticker labels (talas)</li>
		</ul>',
];

$collection_dirty_mousepads = [
	'extends' => '_layouts.single-dirty_mousepads',
	'path'    => 'o__o/{collection}/{slug}',
	'sort'    => '-id',
	'items'   => [
		[
			'id'              => 'jkk_000000_1_u',
			'title'           => 'Echo #00',
			'slug'            => 'echo_00',
			'medium'          => 'oil and dirt on paper',
			'nice_date'       => '2005–2007?',
			'height'          => 8.5,
			'width'           => 11,
			'units'           => 'in',
			'small_height_px' => 242/2,
			'small_width_px'  => 310/2,
			'large_height_px' => 938/2,
			'large_width_px'  => 1200/2,
			'location'        => 'flat files',
			'status'          => 'fully rescanned',
			'notes'           => 'unknown date, pre-#1?, used two ways',
			'imgfile'         => 'jk_keller-000000_1_u-echo_00.jpg',
		],
		[
			'id'              => 'jkk_200504_1_u',
			'title'           => 'Echo #01',
			'slug'            => 'echo_01',
			'medium'          => 'oil and dirt on paper',
			'nice_date'       => '2005',
			'height'          => 11,
			'width'           => 8.5,
			'units'           => 'in',
			'small_height_px' => 310/2,
			'small_width_px'  => 242/2,
			'large_height_px' => 1200/2,
			'large_width_px'  => 938/2,
			'location'        => 'flat files',
			'status'          => 'fully rescanned',
			'notes'           => '?–2005 Apr 17',
			'imgfile'         => 'jk_keller-200504_1_u-echo_01.jpg',
		],
		[
			'id'              => 'jkk_200504_2_u',
			'title'           => 'Echo #02',
			'slug'            => 'echo_02',
			'medium'          => 'oil and dirt on paper',
			'nice_date'       => '2005',
			'height'          => 11,
			'width'           => 8.5,
			'units'           => 'in',
			'small_height_px' => 310/2,
			'small_width_px'  => 242/2,
			'large_height_px' => 1200/2,
			'large_width_px'  => 938/2,
			'location'        => 'flat files',
			'status'          => 'fully rescanned',
			'notes'           => '2005 Apr 18–?',
			'imgfile'         => 'jk_keller-200504_2_u-echo_02.jpg',
		],
		[
			'id'              => 'jkk_200505_1_u',
			'title'           => 'Echo #03',
			'slug'            => 'echo_03',
			'medium'          => 'oil and dirt on paper',
			'nice_date'       => '2005',
			'height'          => 14,
			'width'           => 8.5,
			'units'           => 'in',
			'small_height_px' => 392/2,
			'small_width_px'  => 242/2,
			'large_height_px' => 1200/2,
			'large_width_px'  => 744/2,
			'location'        => 'flat files',
			'status'          => '',
			'notes'           => '2005 May 18',
			'imgfile'         => 'jk_keller-200505_1_u-echo_03.jpg',
		],
		[
			'id'              => 'jkk_200507_1_u',
			'title'           => 'Echo #04',
			'slug'            => 'echo_04',
			'medium'          => 'oil and dirt on paper',
			'nice_date'       => '2005',
			'height'          => 14,
			'width'           => 8.5,
			'units'           => 'in',
			'small_height_px' => 392/2,
			'small_width_px'  => 242/2,
			'large_height_px' => 1200/2,
			'large_width_px'  => 744/2,
			'location'        => 'flat files',
			'status'          => '',
			'notes'           => '2005 Jul 20',
			'imgfile'         => 'jk_keller-200507_1_u-echo_04.jpg',
		],
		[
			'id'              => 'jkk_200509_1_u',
			'title'           => 'Echo #05',
			'slug'            => 'echo_05',
			'medium'          => 'oil and dirt on paper',
			'nice_date'       => '2005',
			'height'          => 11,
			'width'           => 8.5,
			'units'           => 'in',
			'small_height_px' => 310/2,
			'small_width_px'  => 242/2,
			'large_height_px' => 1200/2,
			'large_width_px'  => 938/2,
			'location'        => 'flat files',
			'status'          => '',
			'notes'           => '2005 Sep 01',
			'imgfile'         => 'jk_keller-200509_1_u-echo_05.jpg',
		],
		[
			'id'              => 'jkk_200510_1_u',
			'title'           => 'Echo #06',
			'slug'            => 'echo_06',
			'medium'          => 'oil and dirt on paper',
			'nice_date'       => '2005',
			'height'          => 11,
			'width'           => 8.5,
			'units'           => 'in',
			'small_height_px' => 310/2,
			'small_width_px'  => 242/2,
			'large_height_px' => 1200/2,
			'large_width_px'  => 938/2,
			'location'        => 'flat files',
			'status'          => '',
			'notes'           => '2005 Oct 07',
			'imgfile'         => 'jk_keller-200510_1_u-echo_06.jpg',
		],
		[
			'id'              => 'jkk_200600_2_u',
			'title'           => 'Echo #07',
			'slug'            => 'echo_07',
			'medium'          => 'oil and dirt on paper',
			'nice_date'       => '2006',
			'height'          => 8.5,
			'width'           => 11,
			'units'           => 'in',
			'small_height_px' => 242/2,
			'small_width_px'  => 310/2,
			'large_height_px' => 938/2,
			'large_width_px'  => 1200/2,
			'location'        => 'flat files',
			'status'          => '',
			'notes'           => 'unknown dates',
			'imgfile'         => 'jk_keller-200600_2_u-echo_07.jpg',
		],
		[
			'id'              => 'jkk_200606_1_u',
			'title'           => 'Echo #08',
			'slug'            => 'echo_08',
			'medium'          => 'oil and dirt on paper',
			'nice_date'       => '2006',
			'height'          => 11,
			'width'           => 8.5,
			'units'           => 'in',
			'small_height_px' => 310/2,
			'small_width_px'  => 242/2,
			'large_height_px' => 1200/2,
			'large_width_px'  => 938/2,
			'location'        => 'flat files',
			'status'          => 'framed - need to fix frame?',
			'notes'           => '2006<br>
			included in <cite>Modern Drawings: Tracing 100 Years</cite>, Academy Art Museum, Easton, MD',
			'imgfile'         => 'jk_keller-200606_1_u-echo_08.jpg',
		],
		[
			'id'              => 'jkk_200700_1_u',
			'title'           => 'Echo #09',
			'slug'            => 'echo_09',
			'medium'          => 'oil and dirt on paper',
			'nice_date'       => '2007',
			'height'          => 11.375,
			'width'           => 9,
			'units'           => 'in',
			'small_height_px' => 320/2,
			'small_width_px'  => 256/2,
			'large_height_px' => 1200/2,
			'large_width_px'  => 960/2,
			'location'        => 'flat files',
			'status'          => '',
			'notes'           => 'unknown dates',
			'imgfile'         => 'jk_keller-200700_1_u-echo_09.jpg',
		],
		[
			'id'              => 'jkk_200706_1_u',
			'title'           => 'Echo #10',
			'slug'            => 'echo_10',
			'medium'          => 'oil and dirt on paper',
			'nice_date'       => '2007',
			'height'          => 11,
			'width'           => 8.5,
			'units'           => 'in',
			'small_height_px' => 310/2,
			'small_width_px'  => 242/2,
			'large_height_px' => 1200/2,
			'large_width_px'  => 938/2,
			'location'        => 'flat files',
			'status'          => '',
			'notes'           => 'unknown dates',
			'imgfile'         => 'jk_keller-200706_1_u-echo_10.jpg',
		],
		[
			'id'              => 'jkk_200810_1_u',
			'title'           => 'Echo #11',
			'slug'            => 'echo_11',
			'medium'          => 'oil and dirt on paper',
			'nice_date'       => '2008',
			'height'          => 11.375,
			'width'           => 9,
			'units'           => 'in',
			'small_height_px' => 320/2,
			'small_width_px'  => 256/2,
			'large_height_px' => 1200/2,
			'large_width_px'  => 960/2,
			'location'        => 'flat files',
			'status'          => '',
			'notes'           => '?–2008 Oct 08',
			'imgfile'         => 'jk_keller-200810_1_u-echo_11.jpg',
		],
		[
			'id'              => 'jkk_200812_1_u',
			'title'           => 'Echo #12',
			'slug'            => 'echo_12',
			'medium'          => 'oil and dirt on paper',
			'nice_date'       => '2008',
			'height'          => 11,
			'width'           => 8.5,
			'units'           => 'in',
			'small_height_px' => 310/2,
			'small_width_px'  => 242/2,
			'large_height_px' => 1200/2,
			'large_width_px'  => 938/2,
			'location'        => 'flat files',
			'status'          => '',
			'notes'           => '?–2008 Dec 26 (work)',
			'imgfile'         => 'jk_keller-200812_1_u-echo_12.jpg',
		],
		[
			'id'              => 'jkk_200901_2_u',
			'title'           => 'Echo #13',
			'slug'            => 'echo_13',
			'medium'          => 'oil and dirt on paper',
			'nice_date'       => '2009',
			'height'          => 11,
			'width'           => 8.5,
			'units'           => 'in',
			'small_height_px' => 310/2,
			'small_width_px'  => 242/2,
			'large_height_px' => 1200/2,
			'large_width_px'  => 938/2,
			'location'        => 'flat files',
			'status'          => '',
			'notes'           => '2008 Oct 08–2009 Jan 08 (home)',
			'imgfile'         => 'jk_keller-200901_2_u-echo_13.jpg',
		],
		[
			'id'              => 'jkk_200907_1_u',
			'title'           => 'Echo #14',
			'slug'            => 'echo_14',
			'medium'          => 'oil and dirt on paper',
			'nice_date'       => '2009',
			'height'          => 11.375,
			'width'           => 9,
			'units'           => 'in',
			'small_height_px' => 320/2,
			'small_width_px'  => 256/2,
			'large_height_px' => 1200/2,
			'large_width_px'  => 960/2,
			'location'        => 'flat files',
			'status'          => '',
			'notes'           => '2009 Jan 08–2009 Jul 07 (home)',
			'imgfile'         => 'jk_keller-200907_1_u-echo_14.jpg',
		],
		[
			'id'              => 'jkk_200912_1_u',
			'title'           => 'Echo #15',
			'slug'            => 'echo_15',
			'medium'          => 'oil and dirt on paper',
			'nice_date'       => '2009',
			'height'          => 11,
			'width'           => 8.5,
			'units'           => 'in',
			'small_height_px' => 310/2,
			'small_width_px'  => 242/2,
			'large_height_px' => 1200/2,
			'large_width_px'  => 938/2,
			'location'        => 'flat files',
			'status'          => 'framed - need to fix frame?',
			'notes'           => '2009 Apr 22–2009 Dec 02<br>
			included in <cite>Modern Drawings: Tracing 100 Years</cite>, Academy Art Museum, Easton, MD',
			'imgfile'         => 'jk_keller-200912_1_u-echo_15.jpg',
		],
		[
			'id'              => 'jkk_200912_2_u',
			'title'           => 'Echo #16',
			'slug'            => 'echo_16',
			'medium'          => 'oil and dirt on paper',
			'nice_date'       => '2009',
			'height'          => 11.375,
			'width'           => 9,
			'units'           => 'in',
			'small_height_px' => 320/2,
			'small_width_px'  => 256/2,
			'large_height_px' => 1200/2,
			'large_width_px'  => 960/2,
			'location'        => 'flat files',
			'status'          => '',
			'notes'           => '2009 Jul 08–2009 Dec 23 (work)',
			'imgfile'         => 'jk_keller-200912_2_u-echo_16.jpg',
		],
		[
			'id'              => 'jkk_201007_1_u',
			'title'           => 'Echo #17',
			'slug'            => 'echo_17',
			'medium'          => 'oil and dirt on paper',
			'nice_date'       => '2010',
			'height'          => 11.375,
			'width'           => 9,
			'units'           => 'in',
			'small_height_px' => 320/2,
			'small_width_px'  => 256/2,
			'large_height_px' => 1200/2,
			'large_width_px'  => 960/2,
			'location'        => 'flat files',
			'status'          => '',
			'notes'           => '2010 Jan 01–2010 Jul 04 (home)',
			'imgfile'         => 'jk_keller-201007_1_u-echo_17.jpg',
		],
		[
			'id'              => 'jkk_201007_2_u',
			'title'           => 'Echo #18',
			'slug'            => 'echo_18',
			'medium'          => 'oil and dirt on paper',
			'nice_date'       => '2010',
			'height'          => 11,
			'width'           => 8.5,
			'units'           => 'in',
			'small_height_px' => 310/2,
			'small_width_px'  => 242/2,
			'large_height_px' => 1200/2,
			'large_width_px'  => 938/2,
			'location'        => 'flat files',
			'status'          => '',
			'notes'           => '2010 Jan 03–2010 Jul 09 (work)',
			'imgfile'         => 'jk_keller-201007_2_u-echo_18.jpg',
		],
		[
			'id'              => 'jkk_201012_1_u',
			'title'           => 'Echo #19',
			'slug'            => 'echo_19',
			'medium'          => 'oil and dirt on paper',
			'nice_date'       => '2010',
			'height'          => 11,
			'width'           => 8.5,
			'units'           => 'in',
			'small_height_px' => 310/2,
			'small_width_px'  => 242/2,
			'large_height_px' => 1200/2,
			'large_width_px'  => 938/2,
			'location'        => 'flat files',
			'status'          => '',
			'notes'           => '2010 Jul 15–2010 Dec 24 (work)',
			'imgfile'         => 'jk_keller-201012_1_u-echo_19.jpg',
		],
		[
			'id'              => 'jkk_201101_1_u',
			'title'           => 'Echo #20',
			'slug'            => 'echo_20',
			'medium'          => 'oil and dirt on paper',
			'nice_date'       => '2011',
			'height'          => 10.5,
			'width'           => 8,
			'units'           => 'in',
			'small_height_px' => 296/2,
			'small_width_px'  => 230/2,
			'large_height_px' => 1200/2,
			'large_width_px'  => 926/2,
			'location'        => 'flat files',
			'status'          => '',
			'notes'           => '2010 Jul 29–2011',
			'imgfile'         => 'jk_keller-201101_1_u-echo_20.jpg',
		],
		[
			'id'              => 'jkk_201107_1_u',
			'title'           => 'Echo #21',
			'slug'            => 'echo_21',
			'medium'          => 'oil and dirt on paper',
			'nice_date'       => '2011',
			'height'          => 11,
			'width'           => 8.5,
			'units'           => 'in',
			'small_height_px' => 310/2,
			'small_width_px'  => 242/2,
			'large_height_px' => 1200/2,
			'large_width_px'  => 938/2,
			'location'        => 'flat files',
			'status'          => '',
			'notes'           => '2011 Jan 02–2011 Jul 15 (work)',
			'imgfile'         => 'jk_keller-201107_1_u-echo_21.jpg',
		],
		[
			'id'              => 'jkk_201207_1_u',
			'title'           => 'Echo #22',
			'slug'            => 'echo_22',
			'medium'          => 'oil and dirt on paper',
			'nice_date'       => '2012',
			'height'          => 12,
			'width'           => 9,
			'units'           => 'in',
			'small_height_px' => 338/2,
			'small_width_px'  => 256/2,
			'large_height_px' => 1200/2,
			'large_width_px'  => 912/2,
			'location'        => 'flat files',
			'status'          => '',
			'notes'           => '2011 Jul 30–2012 Jul 30 (work)',
			'imgfile'         => 'jk_keller-201207_1_u-echo_22.jpg',
		],
		[
			'id'              => 'jkk_201212_1_u',
			'title'           => 'Echo #23',
			'slug'            => 'echo_23',
			'medium'          => 'oil and dirt on paper',
			'nice_date'       => '2012',
			'height'          => 11,
			'width'           => 8.5,
			'units'           => 'in',
			'small_height_px' => 310/2,
			'small_width_px'  => 242/2,
			'large_height_px' => 1200/2,
			'large_width_px'  => 938/2,
			'location'        => 'flat files',
			'status'          => '',
			'notes'           => '2012 (work)',
			'imgfile'         => 'jk_keller-201212_1_u-echo_23.jpg',
		],
		[
			'id'              => 'jkk_201303_1_u',
			'title'           => 'Echo #24',
			'slug'            => 'echo_24',
			'medium'          => 'oil and dirt on paper',
			'nice_date'       => '2013',
			'height'          => 11,
			'width'           => 8.5,
			'units'           => 'in',
			'small_height_px' => 310/2,
			'small_width_px'  => 242/2,
			'large_height_px' => 1200/2,
			'large_width_px'  => 938/2,
			'location'        => 'flat files',
			'status'          => '',
			'notes'           => '2012 Sep 08–2013 Mar 30 (home)',
			'imgfile'         => 'jk_keller-201303_1_u-echo_24.jpg',
		],
		[
			'id'              => 'jkk_201308_1_u',
			'title'           => 'Echo #25',
			'slug'            => 'echo_25',
			'medium'          => 'oil and dirt on paper',
			'nice_date'       => '2013',
			'height'          => 11,
			'width'           => 8.5,
			'units'           => 'in',
			'small_height_px' => 310/2,
			'small_width_px'  => 242/2,
			'large_height_px' => 1200/2,
			'large_width_px'  => 938/2,
			'location'        => 'flat files',
			'status'          => '',
			'notes'           => '2013 Feb 20–2013 Aug 20 (work)',
			'imgfile'         => 'jk_keller-201308_1_u-echo_25.jpg',
		],
		[
			'id'              => 'jkk_201404_2_u',
			'title'           => 'Echo #26',
			'slug'            => 'echo_26',
			'medium'          => 'oil and dirt on paper',
			'nice_date'       => '2014',
			'height'          => 11,
			'width'           => 8.5,
			'units'           => 'in',
			'small_height_px' => 310/2,
			'small_width_px'  => 242/2,
			'large_height_px' => 1200/2,
			'large_width_px'  => 938/2,
			'location'        => 'flat files',
			'status'          => 'fully rescanned',
			'notes'           => 'unknown dates?',
			'imgfile'         => 'jk_keller-201404_2_u-echo_26.jpg',
		],
		[
			'id'              => 'jkk_201404_3_u',
			'title'           => 'Echo #27',
			'slug'            => 'echo_27',
			'medium'          => 'oil and dirt on paper',
			'nice_date'       => '2014',
			'height'          => 12,
			'width'           => 9,
			'units'           => 'in',
			'small_height_px' => 338/2,
			'small_width_px'  => 256/2,
			'large_height_px' => 1200/2,
			'large_width_px'  => 912/2,
			'location'        => 'flat files',
			'status'          => '',
			'notes'           => 'unknown dates?',
			'imgfile'         => 'jk_keller-201404_3_u-echo_27.jpg',
		],
		[
			'id'              => 'jkk_201410_2_u',
			'title'           => 'Echo #28',
			'slug'            => 'echo_28',
			'medium'          => 'oil and dirt on paper',
			'nice_date'       => '2014',
			'height'          => 11,
			'width'           => 8.5,
			'units'           => 'in',
			'small_height_px' => 310/2,
			'small_width_px'  => 242/2,
			'large_height_px' => 1200/2,
			'large_width_px'  => 938/2,
			'location'        => 'flat files',
			'status'          => 'fully rescanned',
			'notes'           => 'unknown dates?',
			'imgfile'         => 'jk_keller-201410_2_u-echo_28.jpg',
		],
		[
			'id'              => 'jkk_201503_1_u',
			'title'           => 'Echo #29',
			'slug'            => 'echo_29',
			'medium'          => 'oil and dirt on paper',
			'nice_date'       => '2015',
			'height'          => 11,
			'width'           => 8.5,
			'units'           => 'in',
			'small_height_px' => 310/2,
			'small_width_px'  => 242/2,
			'large_height_px' => 1200/2,
			'large_width_px'  => 938/2,
			'location'        => 'flat files',
			'status'          => '',
			'notes'           => '2014 Oct–2015 Mar 07',
			'imgfile'         => 'jk_keller-201503_1_u-echo_29.jpg',
		],
		[
			'id'              => 'jkk_201512_1_u',
			'title'           => 'Echo #30',
			'slug'            => 'echo_30',
			'medium'          => 'oil and dirt on paper',
			'nice_date'       => '2015',
			'height'          => 11,
			'width'           => 8.5,
			'units'           => 'in',
			'small_height_px' => 310/2,
			'small_width_px'  => 242/2,
			'large_height_px' => 1200/2,
			'large_width_px'  => 938/2,
			'location'        => 'flat files',
			'status'          => 'fully rescanned',
			'notes'           => '?–2015 Dec 31',
			'imgfile'         => 'jk_keller-201512_1_u-echo_30.jpg',
		],
		[
			'id'              => 'jkk_201912_3_u',
			'title'           => 'Echo #31',
			'slug'            => 'echo_31',
			'medium'          => 'oil and dirt on paper',
			'nice_date'       => '2019',
			'height'          => 11,
			'width'           => 8.5,
			'units'           => 'in',
			'small_height_px' => 310/2,
			'small_width_px'  => 242/2,
			'large_height_px' => 1200/2,
			'large_width_px'  => 938/2,
			'location'        => '?flat files?',
			'status'          => 'fully rescanned',
			'notes'           => '2018_12_29-2019_12_31-home',
			'imgfile'         => 'jk_keller-201912_3_u-echo_31.jpg',
		],
	],
];
?>
2018_12_29-2019_12_31-home
