<?php

$series_dots_dots_dots = [
	'slug'        => 'dots_dots_dots',
	'js'          => null,
	'title'       => 'It Takes Me a Long Time to Say Nothing',
	'subtitle'    => 'dot drawings',
	'nice_date'   => '2009–',
	'status'      => '',
	'hidden'      => '',
	'description' => 'Lots & lots of dots in spots',
	'notes'       => 'included in Chattanooga exhibition.',
	'to_dos'      => '<li>Readhere stickers to paper</li>
		<li>grind paint off rods</li>
		<li>repaint rods for hanging</li>
		<li>get other binder coil colors?</li>
		<li>reshoot in good light</li>
		<li>finish __FUL</li>
		<li>more... big dots</li>',
];

$collection_dots_dots_dots = [
	'extends' => '_layouts.single-dots_dots_dots',
	'path'    => 'o__o/{collection}/{slug}',
	'sort'    => '-id',
	'items'   => [
		[
			'id'              => 'jkk_200900_1_u',
			'title'           => '',
			'subtitle'        => '',
			'slug'            => 'dots_s',
			'medium'          => 'sticker dots on paper',
			'date'            => '2009',
			'height'          => 0,
			'width'           => 0,
			'small_height_px' => 0*16,
			'small_width_px'  => 0*16,
			'large_height_px' => 0*40,
			'large_width_px'  => 0*40,
			'units'           => '',
			'location'        => 'in a studio pile somewhere',
			'status'          => '',
			'notes'           => 'S',
			'imgfile'         => '',
		],
		[
			'id'              => 'jkk_201408_7_u',
			'title'           => '',
			'slug'            => 'dots_est',
			'medium'          => 'sticker dots on paper',
			'date'            => '2014',
			'height'          => 12,
			'width'           => 18,
			'small_height_px' => 12*16,
			'small_width_px'  => 18*16,
			'large_height_px' => 12*40,
			'large_width_px'  => 18*40,
			'units'           => 'in',
			'location'        => 'studio',
			'status'          => '',
			'notes'           => '...EST',
			'imgfile'         => 'jk_keller-201408_7_u-dots_est-web-temp.jpg',
		],
		[
			'id'              => 'jkk_201408_3_u',
			'title'           => '',
			'subtitle'        => '...US...',
			'slug'            => 'dots_us',
			'medium'          => 'sticker dots on paper',
			'date'            => '2014',
			'height'          => 12,
			'width'           => 18,
			'small_height_px' => 12*16,
			'small_width_px'  => 18*16,
			'large_height_px' => 12*40,
			'large_width_px'  => 18*40,
			'units'           => 'in',
			'location'        => 'K & U?',
			'status'          => 'gift',
			'notes'           => '',
			'imgfile'         => 'jk_keller-201408_3_u-dots_us-web-temp.jpg',
		],
		[
			'id'              => 'jkk_201408_6_u',
			'title'           => '',
			'subtitle'        => 'AND',
			'slug'            => 'dots_and',
			'medium'          => 'sticker dots on paper',
			'date'            => '2014',
			'height'          => 18,
			'width'           => 24,
			'small_height_px' => 18*16,
			'small_width_px'  => 24*16,
			'large_height_px' => 18*40,
			'large_width_px'  => 24*40,
			'units'           => 'in',
			'location'        => 'JD?',
			'status'          => 'gift',
			'notes'           => '',
			'imgfile'         => 'jk_keller-201408_6_u-dots_and-web-temp.jpg',
		],
		[
			'id'              => 'jkk_201509_3_u',
			'title'           => '',
			'subtitle'        => 'H',
			'slug'            => 'dots_h',
			'medium'          => 'sticker dots on paper',
			'date'            => '2015',
			'height'          => 8.25,
			'width'           => 6.25,
			'small_height_px' => 8.25*16,
			'small_width_px'  => 6.25*16,
			'large_height_px' => 8.25*40,
			'large_width_px'  => 6.25*40,
			'units'           => 'in',
			'location'        => 'Chattanooga person',
			'status'          => 'gift',
			'notes'           => '2015 Sep 18',
			'imgfile'         => 'jk_keller-201509_3_u-dots_h-web.jpg',
		],
		[
			'id'              => 'jkk_201408_4_u',
			'title'           => '',
			'subtitle'        => 'BUT',
			'slug'            => 'dots_but',
			'medium'          => 'sticker dots on paper',
			'date'            => '2014',
			'height'          => 18,
			'width'           => 24,
			'small_height_px' => 18*16,
			'small_width_px'  => 24*16,
			'large_height_px' => 18*40,
			'large_width_px'  => 24*40,
			'units'           => 'in',
			'location'        => 'studio',
			'status'          => '',
			'notes'           => '',
			'imgfile'         => 'jk_keller-201408_4_u-dots_but-web-temp.jpg',
		],
		[
			'id'              => 'jkk_201408_5_u',
			'title'           => '',
			'subtitle'        => 'MIS...',
			'slug'            => 'dots_mis',
			'medium'          => 'sticker dots on paper',
			'date'            => '2014',
			'height'          => 12,
			'width'           => 18,
			'small_height_px' => 12*16,
			'small_width_px'  => 18*16,
			'large_height_px' => 12*40,
			'large_width_px'  => 18*40,
			'units'           => 'in',
			'location'        => 'studio',
			'status'          => '',
			'notes'           => '',
			'imgfile'         => 'jk_keller-201408_5_u-dots_mis-web-temp.jpg',
		],
		[
			'id'              => 'jkk_201408_2_u',
			'title'           => '',
			'subtitle'        => '...FUL',
			'slug'            => 'dots_ful',
			'medium'          => 'sticker dots on paper',
			'date'            => '2014',
			'height'          => 0,
			'width'           => 0,
			'small_height_px' => 0*16,
			'small_width_px'  => 0*16,
			'large_height_px' => 0*40,
			'large_width_px'  => 0*40,
			'units'           => '',
			'location'        => 'studio',
			'status'          => 'to finish',
			'notes'           => '',
			'imgfile'         => '',
		],
		[
			'id'              => 'jkk_201408_1_u',
			'title'           => '',
			'subtitle'        => 'RE...',
			'slug'            => 'dots_re',
			'medium'          => 'sticker dots on paper',
			'date'            => '2014',
			'height'          => 12,
			'width'           => 18,
			'small_height_px' => 12*16,
			'small_width_px'  => 18*16,
			'large_height_px' => 12*40,
			'large_width_px'  => 18*40,
			'units'           => 'in',
			'location'        => 'studio',
			'status'          => '',
			'notes'           => '',
			'imgfile'         => 'jk_keller-201408_1_u-dots_re-web-temp.jpg',
		],
		[
			'id'              => 'jkk_201404_1_u',
			'title'           => '',
			'subtitle'        => 'Infinity',
			'slug'            => 'dots_infinity',
			'medium'          => 'sticker dots on paper',
			'date'            => '2014',
			'height'          => 5,
			'width'           => 7,
			'small_height_px' => 5*16,
			'small_width_px'  => 7*16,
			'large_height_px' => 5*40,
			'large_width_px'  => 7*40,
			'units'           => 'in',
			'location'        => 'England auction',
			'status'          => 'donation',
			'notes'           => '',
			'imgfile'         => 'jk_keller-201404_1_u-dots_infinity-web.jpg',
		],
	],
];
?>
