<?php

$series_dots_dots_dots = [
	'slug'        => 'dots_dots_dots',
	'js'          => null,
	'title'       => 'It Takes Me a Long Time to Say Nothing',
	'nice_date'   => '2009–2015',
	'status'      => '',
	'hidden'      => '',
	'description' => 'Lots & lots of dots in spots',
	'notes'       => '',
	'prj_notes'       => 'included in <cite>We Keep Having This Conversation</cite>',

	'meta_description'  => 'Lots & lots of dots in spots',
	'open_graph_image'  => 'https://jk-keller.com/o__o/dots_dots_dots/x__x/social/1200x630/jk_keller-201408_6_u-dots_and.jpg',
	'twitter_image'     => 'https://jk-keller.com/o__o/dots_dots_dots/x__x/social/1024x512/jk_keller-201404_1_u-dots_infinity.jpg',

	'to_dos'      => '<li>Readhere stickers to paper</li>
		<li>grind paint off rods</li>
		<li>repaint rods for hanging</li>
		<li>get other binder coil colors?</li>
		<li>reshoot in good light</li>
		<li>finish __FUL</li>
		<li>more... big dots</li>',
];

$collection_dots_dots_dots = [
	'path'    => 'o__o/{collection}/{slug}',
	'sort'    => '-sort_date',
	'extends'          => '_layouts.single-image_viewer',

	'series_info'         => $series_dots_dots_dots,

	'items'   => [
		[
			'id'              => 'jkk_201509_3_u',
			'title'           => '',
			'subtitle'        => 'H',
			'slug'            => 'dots_h',
			'medium'          => 'sticker dots on paper',
			'sort_date'       => '2015_09_18',
			'nice_date'       => '2015',
			'height'          => 8.25,
			'width'           => 6.25,
			'units'           => 'in',
			'small_height_px' => 256/2,
			'small_width_px'  => 200/2,
			'large_height_px' => 1200/2,
			'large_width_px'  => 936/2,
			'location'        => 'Chattanooga',
			'status'          => 'gift',
			'notes'           => '',
			'imgfile'         => 'jk_keller-201509_3_u-dots_h.jpg',
		],
		[
			'id'              => 'jkk_201408_7_u',
			'title'           => '',
			'subtitle'        => '...EST',
			'slug'            => 'dots_est',
			'medium'          => 'sticker dots on paper',
			'sort_date'       => '2014_08_07',
			'nice_date'       => '2014',
			'height'          => 12,
			'width'           => 18,
			'units'           => 'in',
			'small_height_px' => 384/2,
			'small_width_px'  => 576/2,
			'large_height_px' => 800/2,
			'large_width_px'  => 1200/2,
			'location'        => 'flat files',
			'status'          => '',
			'notes'           => 'included in <cite>We Keep Having This Conversation</cite>',
			'imgfile'         => 'jk_keller-201408_7_u-dots_est.jpg',
		],
		[
			'id'              => 'jkk_201408_6_u',
			'title'           => '',
			'subtitle'        => 'AND',
			'slug'            => 'dots_and',
			'medium'          => 'sticker dots on paper',
			'sort_date'       => '2014_08_06',
			'nice_date'       => '2014',
			'height'          => 18,
			'width'           => 24,
			'units'           => 'in',
			'small_height_px' => 576/2,
			'small_width_px'  => 768/2,
			'large_height_px' => 900/2,
			'large_width_px'  => 1200/2,
			'location'        => 'JD?',
			'status'          => 'gift',
			'notes'           => 'included in <cite>We Keep Having This Conversation</cite>',
			'imgfile'         => 'jk_keller-201408_6_u-dots_and.jpg',
		],
		[
			'id'              => 'jkk_201408_5_u',
			'title'           => '',
			'subtitle'        => 'MIS...',
			'slug'            => 'dots_mis',
			'medium'          => 'sticker dots on paper',
			'sort_date'       => '2014_08_05',
			'nice_date'       => '2014',
			'height'          => 12,
			'width'           => 18,
			'units'           => 'in',
			'small_height_px' => 384/2,
			'small_width_px'  => 576/2,
			'large_height_px' => 800/2,
			'large_width_px'  => 1200/2,
			'location'        => 'flat files',
			'status'          => '',
			'notes'           => 'included in <cite>We Keep Having This Conversation</cite>',
			'imgfile'         => 'jk_keller-201408_5_u-dots_mis.jpg',
		],
		[
			'id'              => 'jkk_201408_4_u',
			'title'           => '',
			'subtitle'        => 'BUT',
			'slug'            => 'dots_but',
			'medium'          => 'sticker dots on paper',
			'sort_date'       => '2014_08_04',
			'nice_date'       => '2014',
			'height'          => 18,
			'width'           => 24,
			'units'           => 'in',
			'small_height_px' => 576/2,
			'small_width_px'  => 768/2,
			'large_height_px' => 900/2,
			'large_width_px'  => 1200/2,
			'location'        => 'flat files',
			'status'          => '',
			'notes'           => 'included in <cite>We Keep Having This Conversation</cite>',
			'imgfile'         => 'jk_keller-201408_4_u-dots_but.jpg',
		],
		[
			'id'              => 'jkk_201408_3_u',
			'title'           => '',
			'subtitle'        => '...US...',
			'slug'            => 'dots_us',
			'medium'          => 'sticker dots on paper',
			'sort_date'       => '2014_08_03',
			'nice_date'       => '2014',
			'height'          => 12,
			'width'           => 18,
			'units'           => 'in',
			'small_height_px' => 384/2,
			'small_width_px'  => 576/2,
			'large_height_px' => 800/2,
			'large_width_px'  => 1200/2,
			'location'        => 'K & U?',
			'status'          => 'gift',
			'notes'           => 'included in <cite>We Keep Having This Conversation</cite>',
			'imgfile'         => 'jk_keller-201408_3_u-dots_us.jpg',
		],
		// [
		// 	'extends'         => '_layouts.single-image_viewer',
		// 	'id'              => 'jkk_201408_2_u',
		// 	'title'           => '',
		// 	'subtitle'        => '...FUL',
		// 	'slug'            => 'dots_ful',
		// 	'medium'          => 'sticker dots on paper',
		// 	'nice_date'       => '2014',
		// 	'height'          => 0,
		// 	'width'           => 0,
		// 	'small_height_px' => 0*16,
		// 	'small_width_px'  => 0*16,
		// 	'large_height_px' => 0*40,
		// 	'large_width_px'  => 0*40,
		// 	'units'           => '',
		// 	'location'        => 'flat files',
		// 	'status'          => 'to finish',
		// 	'notes'           => '',
		// 	'imgfile'         => '',
		// ],
		[
			'id'              => 'jkk_201408_1_u',
			'title'           => '',
			'subtitle'        => 'RE...',
			'slug'            => 'dots_re',
			'medium'          => 'sticker dots on paper',
			'sort_date'       => '2014_08_01',
			'nice_date'       => '2014',
			'height'          => 12,
			'width'           => 18,
			'units'           => 'in',
			'small_height_px' => 384/2,
			'small_width_px'  => 576/2,
			'large_height_px' => 800/2,
			'large_width_px'  => 1200/2,
			'location'        => 'flat files',
			'status'          => '',
			'notes'           => 'included in <cite>We Keep Having This Conversation</cite>',
			'imgfile'         => 'jk_keller-201408_1_u-dots_re.jpg',
		],
		[
			'id'              => 'jkk_201404_1_u',
			'title'           => '',
			'subtitle'        => 'Infinity',
			'slug'            => 'dots_infinity',
			'medium'          => 'sticker dots on paper',
			'sort_date'       => '2014_04_01',
			'nice_date'       => '2014',
			'height'          => 5,
			'width'           => 7,
			'units'           => 'in',
			'small_height_px' => 150/2,
			'small_width_px'  => 224/2,
			'large_height_px' => 802/2,
			'large_width_px'  => 1200/2,
			'location'        => 'England',
			'status'          => 'donation',
			'notes'           => '',
			'imgfile'         => 'jk_keller-201404_1_u-dots_infinity.jpg',
		],
		[
			'id'              => 'jkk_200900_1_u',
			'title'           => '',
			'subtitle'        => 'S',
			'slug'            => 'dots_s',
			'medium'          => 'sticker dots on paper',
			'sort_date'       => '2009_00_01',
			'nice_date'       => '2009',
			'height'          => 7,
			'width'           => 5,
			'units'           => 'in',
			'small_height_px' => 194/2,
			'small_width_px'  => 138/2,
			'large_height_px' => 1200/2,
			'large_width_px'  => 852/2,
			'location'        => 'in some studio pile',
			'status'          => '',
			'notes'           => '',
			'imgfile'         => 'jk_keller-200900_1_u-dots_s.jpg',
		],
	],
];
?>
