<?php
$max_horizon_offset = 200;

function get_sixteenths($a_Value) {
	$t_integer = floor(floor($a_Value * 16.0 + 0.5) / 16.0);
	$t_mod = floor($a_Value * 16.0 + 0.5) % 16.0;

	if ($t_mod == 0) {
		$sixteen = $t_integer;
	} else if ($t_mod % 8 == 0) {
		$sixteen = $t_integer.' '.(floor($t_mod/8)).'/2';
	} else if ($t_mod % 4 == 0) {
		$sixteen = $t_integer.' '.(floor($t_mod/4)).'/4';
	} else if ($t_mod % 2 == 0) {
		$sixteen = $t_integer.' '.(floor($t_mod/2)).'/8';
	} else {
		$sixteen = $t_integer.' '.$t_mod.'/16';
	}
	// return (floor($a_Value * 16.0 + 0.5) / 16.0).':'.$sixteen;
	return $sixteen;
}

$series_flat_mountains = [
	'slug'        => 'flat_mountains',
	'js'          => null,
	'title'       => 'Tantamounts',
	'nice_date'   => '2008–',
	'status'      => '',
	'description' => 'Mountains computationally reconfigured to a flat horizon.',
	'notes'       => 'more tk',
	'meta_description'  => 'Mountains computationally reconfigured to a flat horizon.',
	'open_graph_image'  => 'https://jk-keller.com/o__o/flat_mountains/x__x/social/1200x630/jk_keller-tantamounts.jpg',
	'twitter_image'     => 'https://jk-keller.com/o__o/flat_mountains/x__x/social/1024x512/jk_keller-tantamounts.jpg',
];

$collection_flat_mountains = [
	'path'        => 'o__o/{collection}/{slug}',
	'sort'        => '-sort_date',
	'extends'     => '_layouts.single-image_viewer',

	'series_info' => $series_flat_mountains,

	'items'   => [
		[
			'id'              => 'jkk_200801_3',
			'title'           => 'Tantamount Three Valley',
			'slug'            => 'three_valley',
			'medium'          => 'print on cut aluminum',
			'sort_date'       => '2008_01_03',
			'nice_date'       => '2008',
			'height'          => get_sixteenths(1476/150),
			'width'           =>  8,
			'units'           => 'in',
			'small_height_px' =>  296/2,
			'small_width_px'  =>  240/2,
			'large_height_px' =>  1476/2,
			'large_width_px'  =>  1200/2,
			'imgfile'         => 'jk_keller-200801_3-tantamount-three_valley',
			'offset_top_px'   =>  round(($max_horizon_offset - 128)/2),
			'location'        => 'digital',
			'status'          => '',
		],
		[
			'id'              => 'jkk_200809_2',
			'title'           => 'Tantamount Paramount (2008)',
			'slug'            => 'paramount_2008',
			'medium'          => 'print on cut aluminum',
			'sort_date'       => '2008_09_02',
			'nice_date'       => '2008',
			'height'          => get_sixteenths(942/150),
			'width'           =>  8,
			'units'           => 'in',
			'small_height_px' =>  188/2,
			'small_width_px'  =>  240/2,
			'large_height_px' =>  942/2,
			'large_width_px'  =>  1200/2,
			'imgfile'         => 'jk_keller-200809_2-tantamount-paramount-2008',
			'offset_top_px'   =>  round(($max_horizon_offset - 107)/2),
			'location'        => 'digital',
			'status'          => '',
		],
		[
			'id'              => 'jkk_200908_1',
			'title'           => 'Tantamount Rushmore',
			'slug'            => 'rushmore',
			'medium'          => 'print on cut aluminum',
			'sort_date'       => '2009_08_01',
			'nice_date'       => '2009',
			'height'          => get_sixteenths(1110/150),
			'width'           =>  8,
			'units'           => 'in',
			'small_height_px' =>  222/2,
			'small_width_px'  =>  240/2,
			'large_height_px' =>  1110/2,
			'large_width_px'  =>  1200/2,
			'imgfile'         => 'jk_keller-200908_1-tantamount-rushmore',
			'offset_top_px'   =>  round(($max_horizon_offset - 86)/2),
			'location'        => 'digital',
			'status'          => '',
		],
		[
			'id'              => 'jkk_200909_1',
			'title'           => 'Tantamount Fuji',
			'subtitle'        => '36 Views of Mt. Fuji (18)',
			'slug'            => '36_views_fuji_18',
			'medium'          => 'print on cut aluminum',
			'sort_date'       => '2009_09_01',
			'nice_date'       => '2009',
			'height'          => get_sixteenths(1060/150),
			'width'           =>  8,
			'units'           => 'in',
			'small_height_px' =>  212/2,
			'small_width_px'  =>  240/2,
			'large_height_px' =>  1060/2,
			'large_width_px'  =>  1200/2,
			'imgfile'         => 'jk_keller-200909_1-tantamount-36_views_fuji_18',
			'offset_top_px'   =>  round(($max_horizon_offset - 63)/2),
			'location'        => 'flat files',
			'status'          => '',
			'notes'           => 'included in <cite>Notes on a New Nature</cite> and <cite>New Aesthetics</cite>',
		],
		[
			'id'              => 'jkk_200910_1',
			'title'           => 'Tantamount Matterhorn Riffelsee',
			'slug'            => 'matterhorn_riffelsee',
			'medium'          => 'print on cut aluminum',
			'sort_date'       => '2009_10_01',
			'nice_date'       => '2009',
			'height'          => get_sixteenths(2240/150),
			'width'           =>  8,
			'units'           => 'in',
			'small_height_px' =>  448/2,
			'small_width_px'  =>  240/2,
			'large_height_px' =>  2240/2,
			'large_width_px'  =>  1200/2,
			'imgfile'         => 'jk_keller-200910_1-tantamount-matterhorn_riffelsee',
			'offset_top_px'   =>  round(($max_horizon_offset - 177)/2),
			'location'        => 'flat files',
			'status'          => '',
			'notes'           => 'included in <cite>Wonderlijk weefsel</cite>',
		],
		[
			'id'              => 'jkk_200910_2',
			'title'           => 'Tantamount St. Helens',
			'slug'            => 'st_helens',
			'medium'          => 'print on cut aluminum',
			'sort_date'       => '2009_10_02',
			'nice_date'       => '2009',
			'height'          => get_sixteenths(994/150),
			'width'           =>  8,
			'units'           => 'in',
			'small_height_px' =>  200/2,
			'small_width_px'  =>  240/2,
			'large_height_px' =>  994/2,
			'large_width_px'  =>  1200/2,
			'imgfile'         => 'jk_keller-200910_2-tantamount-st_helens',
			'offset_top_px'   =>  round(($max_horizon_offset - 111)/2),
			'location'        => 'flat files',
			'status'          => '',
			'notes'           => 'included in <cite>Notes on a New Nature</cite> and <cite>New Aesthetics</cite>',
		],
		[
			'id'              => 'jkk_200910_5',
			'title'           => 'Tantamount Everest',
			'subtitle'        => '#1',
			'slug'            => 'everest',
			'medium'          => 'print on cut aluminum',
			'sort_date'       => '2009_10_05',
			'nice_date'       => '2009',
			'height'          => get_sixteenths(1026/150),
			'width'           =>  8,
			'units'           => 'in',
			'small_height_px' =>  206/2,
			'small_width_px'  =>  240/2,
			'large_height_px' =>  1026/2,
			'large_width_px'  =>  1200/2,
			'imgfile'         => 'jk_keller-200910_5-tantamount-everest',
			'offset_top_px'   =>  round(($max_horizon_offset - 73)/2),
			'location'        => 'digital',
			'status'          => '',
		],
		[
			'id'              => 'jkk_200910_7',
			'title'           => 'Tantamount Everest',
			'subtitle'        => '#2',
			'slug'            => 'everest_2',
			'medium'          => 'print on cut aluminum',
			'sort_date'       => '2009_10_07',
			'nice_date'       => '2009',
			'height'          => get_sixteenths(1026/150),
			'width'           =>  8,
			'units'           => 'in',
			'small_height_px' =>  206/2,
			'small_width_px'  =>  240/2,
			'large_height_px' =>  1026/2,
			'large_width_px'  =>  1200/2,
			'imgfile'         => 'jk_keller-200910_7-tantamount-everest_02',
			'offset_top_px'   =>  round(($max_horizon_offset - 68)/2),
			'location'        => 'flat files',
			'status'          => '',
			'notes'           => 'included in <cite>Notes on a New Nature</cite>',
		],
		[
			'id'              => 'jkk_200910_8',
			'title'           => 'Tantamount Fuji',
			'slug'            => 'fuji',
			'medium'          => 'print on cut aluminum',
			'sort_date'       => '2009_10_08',
			'nice_date'       => '2009',
			'height'          => get_sixteenths(1004/150),
			'width'           =>  8,
			'units'           => 'in',
			'small_height_px' =>  202/2,
			'small_width_px'  =>  240/2,
			'large_height_px' =>  1004/2,
			'large_width_px'  =>  1200/2,
			'imgfile'         => 'jk_keller-200910_8-tantamount-fuji_f_105',
			'offset_top_px'   =>  round(($max_horizon_offset - 79)/2),
			'location'        => 'digital',
			'status'          => '',
		],
		[
			'id'              => 'jkk_200910_9',
			'title'           => 'Tantamount Denali',
			'slug'            => 'denali',
			'medium'          => 'print on cut aluminum',
			'sort_date'       => '2009_10_09',
			'nice_date'       => '2009',
			'height'          => get_sixteenths(1052/150),
			'width'           =>  8,
			'units'           => 'in',
			'small_height_px' =>  210/2,
			'small_width_px'  =>  240/2,
			'large_height_px' =>  1052/2,
			'large_width_px'  =>  1200/2,
			'imgfile'         => 'jk_keller-200910_9-tantamount-denali',
			'offset_top_px'   =>  round(($max_horizon_offset - 73)/2),
			'location'        => 'digital',
			'status'          => '',
		],
		[
			'id'              => 'jkk_201004_1',
			'title'           => 'Tantamount South Cheyenne Canyon',
			'slug'            => 'south_cheyenne_canyon',
			'medium'          => 'print on cut aluminum',
			'sort_date'       => '2010_04_01',
			'nice_date'       => '2010',
			'date'            => '',
			'height'          => get_sixteenths(1826/150),
			'width'           =>  8,
			'units'           => 'in',
			'small_height_px' =>  366/2,
			'small_width_px'  =>  240/2,
			'large_height_px' =>  1826/2,
			'large_width_px'  =>  1200/2,
			'imgfile'         => 'jk_keller-201004_1-tantamount-south_cheyenne_canyon',
			'offset_top_px'   =>  round(($max_horizon_offset - 85)/2),
			'location'        => 'flat files',
			'status'          => '',
			'notes'           => 'included in <cite>Wonderlijk weefsel</cite>',
		],
		[
			'id'              => 'jkk_201010_1',
			'title'           => 'Tantamount K2',
			'slug'            => 'k2',
			'medium'          => 'print on cut aluminum',
			'sort_date'       => '2010_10_01',
			'nice_date'       => '2010',
			'height'          => get_sixteenths(2172/150),
			'width'           =>  8,
			'units'           => 'in',
			'small_height_px' =>  434/2,
			'small_width_px'  =>  240/2,
			'large_height_px' =>  2172/2,
			'large_width_px'  =>  1200/2,
			'imgfile'         => 'jk_keller-201010_1-tantamount-k2',
			'offset_top_px'   =>  round(($max_horizon_offset - 162)/2),
			'location'        => 'flat files',
			'status'          => '',
			'notes'           => 'included in <cite>Wonderlijk weefsel</cite>, <cite>Notes on a New Nature</cite>, and <cite>New Aesthetics</cite>',
		],
		[
			'id'              => 'jkk_201010_2',
			'title'           => 'Tantamount Hadley',
			'slug'            => 'hadley',
			'medium'          => 'print on cut aluminum',
			'sort_date'       => '2010_10_02',
			'nice_date'       => '2010',
			'height'          => get_sixteenths(928/150),
			'width'           =>  8,
			'units'           => 'in',
			'small_height_px' =>  186/2,
			'small_width_px'  =>  240/2,
			'large_height_px' =>  928/2,
			'large_width_px'  =>  1200/2,
			'imgfile'         => 'jk_keller-201010_2-tantamount-hadley',
			'offset_top_px'   =>  round(($max_horizon_offset - 76)/2),
			'location'        => 'flat files',
			'status'          => '',
			'notes'           => 'included in <cite>Notes on a New Nature</cite> and <cite>New Aesthetics</cite>',
		],
		[
			'id'              => 'jkk_201010_3',
			'title'           => 'Tantamount Snake River',
			'slug'            => 'adams_snake_river',
			'medium'          => 'print on cut aluminum',
			'sort_date'       => '2010_10_03',
			'nice_date'       => '2010',
			'height'          => get_sixteenths(1122/150),
			'width'           =>  8,
			'units'           => 'in',
			'small_height_px' =>  224/2,
			'small_width_px'  =>  240/2,
			'large_height_px' =>  1122/2,
			'large_width_px'  =>  1200/2,
			'imgfile'         => 'jk_keller-201010_3-tantamount-adams_snake_river',
			'offset_top_px'   =>  round(($max_horizon_offset - 73)/2),
			'location'        => 'flat files',
			'status'          => '',
			'notes'           => 'included in <cite>Notes on a New Nature</cite> and <cite>New Aesthetics</cite>',
		],
		[
			'id'              => 'jkk_201010_4',
			'title'           => 'Tantamount Saint Victoire Barnes',
			'slug'            => 'saint_victoire_barnes',
			'medium'          => 'print on cut aluminum',
			'sort_date'       => '2010_10_04',
			'nice_date'       => '2010',
			'height'          => get_sixteenths(1182/150),
			'width'           =>  8,
			'units'           => 'in',
			'small_height_px' =>  236/2,
			'small_width_px'  =>  240/2,
			'large_height_px' =>  1182/2,
			'large_width_px'  =>  1200/2,
			'imgfile'         => 'jk_keller-201010_4-tantamount-saint_victoire_barnes',
			'offset_top_px'   =>  round(($max_horizon_offset - 74)/2),
			'location'        => 'flat files',
			'status'          => '',
			'notes'           => 'included in <cite>Notes on a New Nature</cite> and <cite>New Aesthetics</cite>',
		],
		[
			'id'              => 'jkk_201010_5',
			'title'           => 'Tantamount Bryce',
			'slug'            => 'bryce',
			'medium'          => 'print on cut aluminum',
			'sort_date'       => '2010_10_05',
			'nice_date'       => '2010',
			'height'          => get_sixteenths(1080/150),
			'width'           =>  8,
			'units'           => 'in',
			'small_height_px' =>  216/2,
			'small_width_px'  =>  240/2,
			'large_height_px' =>  1080/2,
			'large_width_px'  =>  1200/2,
			'imgfile'         => 'jk_keller-201010_5-tantamount-bryce',
			'offset_top_px'   =>  round(($max_horizon_offset - 74)/2),
			'location'        => 'flat files',
			'status'          => '',
			'notes'           => 'included in <cite>Wonderlijk weefsel</cite>, <cite>Notes on a New Nature</cite>, and <cite>New Aesthetics</cite>',
		],
		[
			'id'              => 'jkk_201010_7',
			'title'           => 'Tantamount Day 3 Hills',
			'slug'            => 'day_3_hills',
			'medium'          => 'print on cut aluminum',
			'sort_date'       => '2010_10_07',
			'nice_date'       => '2010',
			'height'          => get_sixteenths(1668/150),
			'width'           =>  8,
			'units'           => 'in',
			'small_height_px' =>  334/2,
			'small_width_px'  =>  240/2,
			'large_height_px' =>  1668/2,
			'large_width_px'  =>  1200/2,
			'imgfile'         => 'jk_keller-201010_7-tantamount-day_3_hills',
			'offset_top_px'   =>  round(($max_horizon_offset - 175)/2),
			'location'        => 'flat files',
			'status'          => '',
			'notes'           => 'included in <cite>Wonderlijk weefsel</cite>',
		],
		[
			'id'              => 'jkk_201010_8',
			'title'           => 'Tantamount Matterhorn',
			'slug'            => 'matterhorn',
			'medium'          => 'print on cut aluminum',
			'sort_date'       => '2010_10_08',
			'nice_date'       => '2010',
			'height'          => get_sixteenths(1310/150),
			'width'           =>  8,
			'units'           => 'in',
			'small_height_px' =>  262/2,
			'small_width_px'  =>  240/2,
			'large_height_px' =>  1310/2,
			'large_width_px'  =>  1200/2,
			'imgfile'         => 'jk_keller-201010_8-tantamount-matterhorn_wild_wonders',
			'offset_top_px'   =>  round(($max_horizon_offset - 70)/2),
			'location'        => 'flat files',
			'status'          => '',
			'notes'           => 'included in <cite>Notes on a New Nature</cite> and <cite>New Aesthetics</cite>',
		],
		[
			'id'              => 'jkk_201303_2',
			'title'           => 'Tantamount Castle Rock, Erebus',
			'slug'            => 'erebus_castle_rock',
			'medium'          => 'print on cut aluminum',
			'sort_date'       => '2013_03_02',
			'nice_date'       => '2013',
			'height'          => get_sixteenths(1000/150),
			'width'           =>  8,
			'units'           => 'in',
			'small_height_px' =>  200/2,
			'small_width_px'  =>  240/2,
			'large_height_px' =>  1000/2,
			'large_width_px'  =>  1200/2,
			'imgfile'         => 'jk_keller-201303_2-tantamount-erebus_castle_rock',
			'offset_top_px'   =>  round(($max_horizon_offset - 89)/2),
			'location'        => 'digital',
			'status'          => '',
		],
		[
			'id'              => 'jkk_201410_8',
			'title'           => 'Tantamount Mac Yosemite',
			'subtitle'        => '#1',
			'slug'            => 'yosemite',
			'medium'          => 'print on cut aluminum',
			'sort_date'       => '2014_10_08',
			'nice_date'       => '2014',
			'height'          => get_sixteenths(1230/150),
			'width'           =>  8,
			'units'           => 'in',
			'small_height_px' =>  246/2,
			'small_width_px'  =>  240/2,
			'large_height_px' =>  1230/2,
			'large_width_px'  =>  1200/2,
			'imgfile'         => 'jk_keller-201410_8-tantamount-yosemite_01',
			'offset_top_px'   =>  round(($max_horizon_offset - 127)/2),
			'location'        => 'digital',
			'status'          => '',
		],
		[
			'id'              => 'jkk_201410_9',
			'title'           => 'Tantamount Mac Yosemite',
			'subtitle'        => '#2',
			'slug'            => 'yosemite_2',
			'medium'          => 'print on cut aluminum',
			'sort_date'       => '2014_10_09',
			'nice_date'       => '2014',
			'height'          => get_sixteenths(990/150),
			'width'           =>  8,
			'units'           => 'in',
			'small_height_px' =>  198/2,
			'small_width_px'  =>  240/2,
			'large_height_px' =>  990/2,
			'large_width_px'  =>  1200/2,
			'imgfile'         => 'jk_keller-201410_9-tantamount-yosemite_02',
			'offset_top_px'   =>  round(($max_horizon_offset - 78)/2),
			'location'        => 'digital',
			'status'          => '',
		],
		[
			'id'              => 'jkk_201410_10',
			'title'           => 'Tantamount Mac Yosemite',
			'subtitle'        => '#3',
			'slug'            => 'yosemite_3',
			'medium'          => 'print on cut aluminum',
			'sort_date'       => '2014_10_10',
			'nice_date'       => '2014',
			'height'          => get_sixteenths(1006/150),
			'width'           =>  8,
			'units'           => 'in',
			'small_height_px' =>  202/2,
			'small_width_px'  =>  240/2,
			'large_height_px' =>  1006/2,
			'large_width_px'  =>  1200/2,
			'imgfile'         => 'jk_keller-201410_10-tantamount-yosemite_03',
			'offset_top_px'   =>  round(($max_horizon_offset - 67)/2),
			'location'        => 'flat files',
			'status'          => '',
			'notes'           => 'included in <cite>Wonderlijk weefsel</cite>',
		],
		[
			'id'              => 'jkk_201410_11',
			'title'           => 'Tantamount Mac Yosemite',
			'subtitle'        => '#4',
			'slug'            => 'yosemite_4',
			'medium'          => 'print on cut aluminum',
			'sort_date'       => '2014_10_11',
			'nice_date'       => '2014',
			'height'          => get_sixteenths(912/150),
			'width'           =>  8,
			'units'           => 'in',
			'small_height_px' =>  182/2,
			'small_width_px'  =>  240/2,
			'large_height_px' =>  912/2,
			'large_width_px'  =>  1200/2,
			'imgfile'         => 'jk_keller-201410_11-tantamount-yosemite_04',
			'offset_top_px'   =>  round(($max_horizon_offset - 80)/2),
			'location'        => 'digital',
			'status'          => '',
		],
		[
			'id'              => 'jkk_201410_12',
			'title'           => 'Tantamount Mac Yosemite',
			'subtitle'        => '#5',
			'slug'            => 'yosemite_5',
			'medium'          => 'print on cut aluminum',
			'sort_date'       => '2014_10_12',
			'nice_date'       => '2014',
			'height'          => get_sixteenths(918/150),
			'width'           =>  8,
			'units'           => 'in',
			'small_height_px' =>  184/2,
			'small_width_px'  =>  240/2,
			'large_height_px' =>  918/2,
			'large_width_px'  =>  1200/2,
			'imgfile'         => 'jk_keller-201410_12-tantamount-yosemite_05',
			'offset_top_px'   =>  round(($max_horizon_offset - 59)/2),
			'location'        => 'digital',
			'status'          => '',
		],
		[
			'id'              => 'jkk_201410_13',
			'title'           => 'Tantamount Mac Fuji',
			'slug'            => 'fuji_2',
			'medium'          => 'print on cut aluminum',
			'sort_date'       => '2014_10_13',
			'nice_date'       => '2014',
			'height'          => get_sixteenths(970/150),
			'width'           =>  8,
			'units'           => 'in',
			'small_height_px' =>  194/2,
			'small_width_px'  =>  240/2,
			'large_height_px' =>  970/2,
			'large_width_px'  =>  1200/2,
			'imgfile'         => 'jk_keller-201410_13-tantamount-fuji-03',
			'offset_top_px'   =>  round(($max_horizon_offset - 85)/2),
			'location'        => 'digital',
			'status'          => '',
		],
		[
			'id'              => 'jkk_201703_1',
			'title'           => 'Tantamount Maat Mons',
			'slug'            => 'maat_mons',
			'medium'          => 'print on cut aluminum',
			'sort_date'       => '2017_03_20',
			'nice_date'       => '2017',
			'height'          => get_sixteenths(1222/150),
			'width'           =>  8,
			'units'           => 'in',
			'small_height_px' =>  244/2,
			'small_width_px'  =>  240/2,
			'large_height_px' =>  1222/2,
			'large_width_px'  =>  1200/2,
			'imgfile'         => 'jk_keller-201703_1-tantamount-maat_mons',
			'offset_top_px'   =>  round(($max_horizon_offset - 79)/2),
			'location'        => 'flat files',
			'status'          => '',
			'notes'           => 'included in <cite>Wonderlijk weefsel</cite>',
		],
		[
			'id'              => 'jkk_201703_4',
			'title'           => 'Tantamount Hodas',
			'slug'            => 'hodas',
			'medium'          => 'print on cut aluminum',
			'sort_date'       => '2017_03_20',
			'nice_date'       => '2017',
			'height'          => get_sixteenths(1492/150),
			'width'           =>  8,
			'units'           => 'in',
			'small_height_px' =>  298/2,
			'small_width_px'  =>  240/2,
			'large_height_px' =>  1492/2,
			'large_width_px'  =>  1200/2,
			'imgfile'         => 'jk_keller-201703_4-tantamount-hodas',
			'offset_top_px'   =>  round(($max_horizon_offset - 134)/2),
			'location'        => 'flat files',
			'status'          => '',
			'notes'           => 'included in <cite>Wonderlijk weefsel</cite>',
		],
		[
			'id'              => 'jkk_201703_5',
			'title'           => 'Tantamount Enlitz',
			'slug'            => 'enlitz',
			'medium'          => 'print on cut aluminum',
			'sort_date'       => '2017_03_05',
			'nice_date'       => '2017',
			'height'          => get_sixteenths(1334/150),
			'width'           =>  8,
			'units'           => 'in',
			'small_height_px' =>  268/2,
			'small_width_px'  =>  240/2,
			'large_height_px' =>  1334/2,
			'large_width_px'  =>  1200/2,
			'imgfile'         => 'jk_keller-201703_5-tantamount-enlitz',
			'offset_top_px'   =>  round(($max_horizon_offset - 148)/2),
			'location'        => 'digital',
			'status'          => '',
		],
		[
			'id'              => 'jkk_201703_6',
			'title'           => 'Tantamount Adobe',
			'slug'            => 'adobe',
			'medium'          => 'print on cut aluminum',
			'sort_date'       => '2017_03_06',
			'nice_date'       => '2017',
			'height'          => get_sixteenths(1076/150),
			'width'           =>  8,
			'units'           => 'in',
			'small_height_px' =>  216/2,
			'small_width_px'  =>  240/2,
			'large_height_px' =>  1076/2,
			'large_width_px'  =>  1200/2,
			'imgfile'         => 'jk_keller-201703_6-tantamount-adobe',
			'offset_top_px'   =>  round(($max_horizon_offset - 117)/2),
			'location'        => 'digital',
			'status'          => '',
		],
		[
			'id'              => 'jkk_201703_7',
			'title'           => 'Tantamount Smits',
			'slug'            => 'smits',
			'medium'          => 'print on cut aluminum',
			'sort_date'       => '2017_03_07',
			'nice_date'       => '2017',
			'height'          => get_sixteenths(886/150),
			'width'           =>  8,
			'units'           => 'in',
			'small_height_px' =>  178/2,
			'small_width_px'  =>  240/2,
			'large_height_px' =>  886/2,
			'large_width_px'  =>  1200/2,
			'imgfile'         => 'jk_keller-201703_7-tantamount-smits',
			'offset_top_px'   =>  round(($max_horizon_offset - 60)/2),
			'location'        => 'digital',
			'status'          => '',
		],





		[
			'id'              => 'jkk_201810_2',
			'title'           => 'Tantamount Mac Mojave',
			'subtitle'        => '#2',
			'slug'            => 'mojave_02',
			'medium'          => 'print on cut aluminum',
			'sort_date'       => '2018_10_02',
			'nice_date'       => '2018',
			'height'          => get_sixteenths(1328/150),
			'width'           =>  8,
			'units'           => 'in',
			'small_height_px' =>  266/2,
			'small_width_px'  =>  240/2,
			'large_height_px' =>  1328/2,
			'large_width_px'  =>  1200/2,
			'imgfile'         => 'jk_keller-201810_2-tantamount-mojave_02',
			'offset_top_px'   =>  round(($max_horizon_offset - 118)/2),
			'location'        => 'digital',
			'status'          => '',
		],
		[
			'id'              => 'jkk_201810_3',
			'title'           => 'Tantamount Mac Mojave',
			'subtitle'        => '#3',
			'slug'            => 'mojave_03',
			'medium'          => 'print on cut aluminum',
			'sort_date'       => '2018_10_03',
			'nice_date'       => '2018',
			'height'          => get_sixteenths(1328/150),
			'width'           =>  8,
			'units'           => 'in',
			'small_height_px' =>  266/2,
			'small_width_px'  =>  240/2,
			'large_height_px' =>  1328/2,
			'large_width_px'  =>  1200/2,
			'imgfile'         => 'jk_keller-201810_3-tantamount-mojave_03',
			'offset_top_px'   =>  round(($max_horizon_offset - 118)/2),
			'location'        => 'digital',
			'status'          => '',
		],
		[
			'id'              => 'jkk_201810_4',
			'title'           => 'Tantamount Mac Mojave',
			'subtitle'        => '#4',
			'slug'            => 'mojave_04',
			'medium'          => 'print on cut aluminum',
			'sort_date'       => '2018_10_04',
			'nice_date'       => '2018',
			'height'          => get_sixteenths(1328/150),
			'width'           =>  8,
			'units'           => 'in',
			'small_height_px' =>  266/2,
			'small_width_px'  =>  240/2,
			'large_height_px' =>  1328/2,
			'large_width_px'  =>  1200/2,
			'imgfile'         => 'jk_keller-201810_4-tantamount-mojave_04',
			'offset_top_px'   =>  round(($max_horizon_offset - 118)/2),
			'location'        => 'digital',
			'status'          => '',
		],
		[
			'id'              => 'jkk_201810_5',
			'title'           => 'Tantamount Mac Mojave',
			'subtitle'        => '#5',
			'slug'            => 'mojave_05',
			'medium'          => 'print on cut aluminum',
			'sort_date'       => '2018_10_05',
			'nice_date'       => '2018',
			'height'          => get_sixteenths(1328/150),
			'width'           =>  8,
			'units'           => 'in',
			'small_height_px' =>  266/2,
			'small_width_px'  =>  240/2,
			'large_height_px' =>  1328/2,
			'large_width_px'  =>  1200/2,
			'imgfile'         => 'jk_keller-201810_5-tantamount-mojave_05',
			'offset_top_px'   =>  round(($max_horizon_offset - 118)/2),
			'location'        => 'digital',
			'status'          => '',
		],
		[
			'id'              => 'jkk_201810_6',
			'title'           => 'Tantamount Mac Mojave',
			'subtitle'        => '#6',
			'slug'            => 'mojave_06',
			'medium'          => 'print on cut aluminum',
			'sort_date'       => '2018_10_06',
			'nice_date'       => '2018',
			'height'          => get_sixteenths(1328/150),
			'width'           =>  8,
			'units'           => 'in',
			'small_height_px' =>  266/2,
			'small_width_px'  =>  240/2,
			'large_height_px' =>  1328/2,
			'large_width_px'  =>  1200/2,
			'imgfile'         => 'jk_keller-201810_6-tantamount-mojave_06',
			'offset_top_px'   =>  round(($max_horizon_offset - 118)/2),
			'location'        => 'digital',
			'status'          => '',
		],
		[
			'id'              => 'jkk_201810_7',
			'title'           => 'Tantamount Mac Mojave',
			'subtitle'        => '#7',
			'slug'            => 'mojave_07',
			'medium'          => 'print on cut aluminum',
			'sort_date'       => '2018_10_07',
			'nice_date'       => '2018',
			'height'          => get_sixteenths(1328/150),
			'width'           =>  8,
			'units'           => 'in',
			'small_height_px' =>  266/2,
			'small_width_px'  =>  240/2,
			'large_height_px' =>  1328/2,
			'large_width_px'  =>  1200/2,
			'imgfile'         => 'jk_keller-201810_7-tantamount-mojave_07',
			'offset_top_px'   =>  round(($max_horizon_offset - 118)/2),
			'location'        => 'digital',
			'status'          => '',
		],
		[
			'id'              => 'jkk_201810_8',
			'title'           => 'Tantamount Mac Mojave',
			'subtitle'        => '#8',
			'slug'            => 'mojave_08',
			'medium'          => 'print on cut aluminum',
			'sort_date'       => '2018_10_08',
			'nice_date'       => '2018',
			'height'          => get_sixteenths(1328/150),
			'width'           =>  8,
			'units'           => 'in',
			'small_height_px' =>  266/2,
			'small_width_px'  =>  240/2,
			'large_height_px' =>  1328/2,
			'large_width_px'  =>  1200/2,
			'imgfile'         => 'jk_keller-201810_8-tantamount-mojave_08',
			'offset_top_px'   =>  round(($max_horizon_offset - 118)/2),
			'location'        => 'digital',
			'status'          => '',
		],
		[
			'id'              => 'jkk_201810_9',
			'title'           => 'Tantamount Mac Mojave',
			'subtitle'        => '#9',
			'slug'            => 'mojave_09',
			'medium'          => 'print on cut aluminum',
			'sort_date'       => '2018_10_09',
			'nice_date'       => '2018',
			'height'          => get_sixteenths(1328/150),
			'width'           =>  8,
			'units'           => 'in',
			'small_height_px' =>  266/2,
			'small_width_px'  =>  240/2,
			'large_height_px' =>  1328/2,
			'large_width_px'  =>  1200/2,
			'imgfile'         => 'jk_keller-201810_9-tantamount-mojave_09',
			'offset_top_px'   =>  round(($max_horizon_offset - 118)/2),
			'location'        => 'digital',
			'status'          => '',
		],
		[
			'id'              => 'jkk_201810_10',
			'title'           => 'Tantamount Mac Mojave',
			'subtitle'        => '#10',
			'slug'            => 'mojave_10',
			'medium'          => 'print on cut aluminum',
			'sort_date'       => '2018_10_10',
			'nice_date'       => '2018',
			'height'          => get_sixteenths(1328/150),
			'width'           =>  8,
			'units'           => 'in',
			'small_height_px' =>  266/2,
			'small_width_px'  =>  240/2,
			'large_height_px' =>  1328/2,
			'large_width_px'  =>  1200/2,
			'imgfile'         => 'jk_keller-201810_10-tantamount-mojave_10',
			'offset_top_px'   =>  round(($max_horizon_offset - 118)/2),
			'location'        => 'digital',
			'status'          => '',
		],
		[
			'id'              => 'jkk_201810_11',
			'title'           => 'Tantamount Mac Mojave',
			'subtitle'        => '#11',
			'slug'            => 'mojave_11',
			'medium'          => 'print on cut aluminum',
			'sort_date'       => '2018_10_11',
			'nice_date'       => '2018',
			'height'          => get_sixteenths(1328/150),
			'width'           =>  8,
			'units'           => 'in',
			'small_height_px' =>  266/2,
			'small_width_px'  =>  240/2,
			'large_height_px' =>  1328/2,
			'large_width_px'  =>  1200/2,
			'imgfile'         => 'jk_keller-201810_11-tantamount-mojave_11',
			'offset_top_px'   =>  round(($max_horizon_offset - 118)/2),
			'location'        => 'digital',
			'status'          => '',
		],
		[
			'id'              => 'jkk_201810_12',
			'title'           => 'Tantamount Mac Mojave',
			'subtitle'        => '#12',
			'slug'            => 'mojave_12',
			'medium'          => 'print on cut aluminum',
			'sort_date'       => '2018_10_12',
			'nice_date'       => '2018',
			'height'          => get_sixteenths(1328/150),
			'width'           =>  8,
			'units'           => 'in',
			'small_height_px' =>  266/2,
			'small_width_px'  =>  240/2,
			'large_height_px' =>  1328/2,
			'large_width_px'  =>  1200/2,
			'imgfile'         => 'jk_keller-201810_12-tantamount-mojave_12',
			'offset_top_px'   =>  round(($max_horizon_offset - 118)/2),
			'location'        => 'digital',
			'status'          => '',
		],
		[
			'id'              => 'jkk_201810_13',
			'title'           => 'Tantamount Mac Mojave',
			'subtitle'        => '#13',
			'slug'            => 'mojave_13',
			'medium'          => 'print on cut aluminum',
			'sort_date'       => '2018_10_13',
			'nice_date'       => '2018',
			'height'          => get_sixteenths(1328/150),
			'width'           =>  8,
			'units'           => 'in',
			'small_height_px' =>  266/2,
			'small_width_px'  =>  240/2,
			'large_height_px' =>  1328/2,
			'large_width_px'  =>  1200/2,
			'imgfile'         => 'jk_keller-201810_13-tantamount-mojave_13',
			'offset_top_px'   =>  round(($max_horizon_offset - 118)/2),
			'location'        => 'digital',
			'status'          => '',
		],
		[
			'id'              => 'jkk_201810_14',
			'title'           => 'Tantamount Mac Mojave',
			'subtitle'        => '#14',
			'slug'            => 'mojave_14',
			'medium'          => 'print on cut aluminum',
			'sort_date'       => '2018_10_14',
			'nice_date'       => '2018',
			'height'          => get_sixteenths(1328/150),
			'width'           =>  8,
			'units'           => 'in',
			'small_height_px' =>  266/2,
			'small_width_px'  =>  240/2,
			'large_height_px' =>  1328/2,
			'large_width_px'  =>  1200/2,
			'imgfile'         => 'jk_keller-201810_14-tantamount-mojave_14',
			'offset_top_px'   =>  round(($max_horizon_offset - 118)/2),
			'location'        => 'digital',
			'status'          => '',
		],
		[
			'id'              => 'jkk_201810_15',
			'title'           => 'Tantamount Mac Mojave',
			'subtitle'        => '#15',
			'slug'            => 'mojave_15',
			'medium'          => 'print on cut aluminum',
			'sort_date'       => '2018_10_15',
			'nice_date'       => '2018',
			'height'          => get_sixteenths(1328/150),
			'width'           =>  8,
			'units'           => 'in',
			'small_height_px' =>  266/2,
			'small_width_px'  =>  240/2,
			'large_height_px' =>  1328/2,
			'large_width_px'  =>  1200/2,
			'imgfile'         => 'jk_keller-201810_15-tantamount-mojave_15',
			'offset_top_px'   =>  round(($max_horizon_offset - 118)/2),
			'location'        => 'digital',
			'status'          => '',
		],
		[
			'id'              => 'jkk_201810_16',
			'title'           => 'Tantamount Mac Mojave',
			'subtitle'        => '#16',
			'slug'            => 'mojave_16',
			'medium'          => 'print on cut aluminum',
			'sort_date'       => '2018_10_16',
			'nice_date'       => '2018',
			'height'          => get_sixteenths(1328/150),
			'width'           =>  8,
			'units'           => 'in',
			'small_height_px' =>  266/2,
			'small_width_px'  =>  240/2,
			'large_height_px' =>  1328/2,
			'large_width_px'  =>  1200/2,
			'imgfile'         => 'jk_keller-201810_16-tantamount-mojave_16',
			'offset_top_px'   =>  round(($max_horizon_offset - 118)/2),
			'location'        => 'digital',
			'status'          => '',
		],
		[
			'id'              => 'jkk_201810_17',
			'title'           => 'Tantamount Mac Mojave',
			'subtitle'        => '#17',
			'slug'            => 'mojave_17',
			'medium'          => 'print on cut aluminum',
			'sort_date'       => '2018_10_17',
			'nice_date'       => '2018',
			'height'          => get_sixteenths(1328/150),
			'width'           =>  8,
			'units'           => 'in',
			'small_height_px' =>  266/2,
			'small_width_px'  =>  240/2,
			'large_height_px' =>  1328/2,
			'large_width_px'  =>  1200/2,
			'imgfile'         => 'jk_keller-201810_17-tantamount-mojave_17',
			'offset_top_px'   =>  round(($max_horizon_offset - 118)/2),
			'location'        => 'digital',
			'status'          => '',
		],






		[
			'id'              => 'jkk_201910_1',
			'title'           => 'Tantamount Mac Catalina',
			'subtitle'        => '#1',
			'slug'            => 'catalina_1',
			'medium'          => 'print on cut aluminum',
			'sort_date'       => '2019_10_01',
			'nice_date'       => '2019',
			'height'          => get_sixteenths(1330/150),
			'width'           =>  8,
			'units'           => 'in',
			'small_height_px' =>  266/2,
			'small_width_px'  =>  240/2,
			'large_height_px' =>  1330/2,
			'large_width_px'  =>  1200/2,
			'imgfile'         => 'jk_keller-201910_1-tantamount-catalina_1',
			'offset_top_px'   =>  round(($max_horizon_offset - 92)/2),
			'location'        => 'digital',
			'status'          => '',
		],
		[
			'id'              => 'jkk_201910_2',
			'title'           => 'Tantamount Mac Catalina',
			'subtitle'        => '#2',
			'slug'            => 'catalina_2',
			'medium'          => 'print on cut aluminum',
			'sort_date'       => '2019_10_02',
			'nice_date'       => '2019',
			'height'          => get_sixteenths(1330/150),
			'width'           =>  8,
			'units'           => 'in',
			'small_height_px' =>  266/2,
			'small_width_px'  =>  240/2,
			'large_height_px' =>  1330/2,
			'large_width_px'  =>  1200/2,
			'imgfile'         => 'jk_keller-201910_2-tantamount-catalina_2',
			'offset_top_px'   =>  round(($max_horizon_offset - 92)/2),
			'location'        => 'digital',
			'status'          => '',
		],
		[
			'id'              => 'jkk_201910_3',
			'title'           => 'Tantamount Mac Catalina',
			'subtitle'        => '#3',
			'slug'            => 'catalina_3',
			'medium'          => 'print on cut aluminum',
			'sort_date'       => '2019_10_03',
			'nice_date'       => '2019',
			'height'          => get_sixteenths(1330/150),
			'width'           =>  8,
			'units'           => 'in',
			'small_height_px' =>  266/2,
			'small_width_px'  =>  240/2,
			'large_height_px' =>  1330/2,
			'large_width_px'  =>  1200/2,
			'imgfile'         => 'jk_keller-201910_3-tantamount-catalina_3',
			'offset_top_px'   =>  round(($max_horizon_offset - 92)/2),
			'location'        => 'digital',
			'status'          => '',
		],
		[
			'id'              => 'jkk_201910_4',
			'title'           => 'Tantamount Mac Catalina',
			'subtitle'        => '#4',
			'slug'            => 'catalina_4',
			'medium'          => 'print on cut aluminum',
			'sort_date'       => '2019_10_04',
			'nice_date'       => '2019',
			'height'          => get_sixteenths(1330/150),
			'width'           =>  8,
			'units'           => 'in',
			'small_height_px' =>  266/2,
			'small_width_px'  =>  240/2,
			'large_height_px' =>  1330/2,
			'large_width_px'  =>  1200/2,
			'imgfile'         => 'jk_keller-201910_4-tantamount-catalina_4',
			'offset_top_px'   =>  round(($max_horizon_offset - 92)/2),
			'location'        => 'digital',
			'status'          => '',
		],
		[
			'id'              => 'jkk_201910_5',
			'title'           => 'Tantamount Mac Catalina',
			'subtitle'        => '#5',
			'slug'            => 'catalina_5',
			'medium'          => 'print on cut aluminum',
			'sort_date'       => '2019_10_05',
			'nice_date'       => '2019',
			'height'          => get_sixteenths(1330/150),
			'width'           =>  8,
			'units'           => 'in',
			'small_height_px' =>  266/2,
			'small_width_px'  =>  240/2,
			'large_height_px' =>  1330/2,
			'large_width_px'  =>  1200/2,
			'imgfile'         => 'jk_keller-201910_5-tantamount-catalina_5',
			'offset_top_px'   =>  round(($max_horizon_offset - 92)/2),
			'location'        => 'digital',
			'status'          => '',
		],
		[
			'id'              => 'jkk_201910_6',
			'title'           => 'Tantamount Mac Catalina',
			'subtitle'        => '#6',
			'slug'            => 'catalina_6',
			'medium'          => 'print on cut aluminum',
			'sort_date'       => '2019_10_06',
			'nice_date'       => '2019',
			'height'          => get_sixteenths(1330/150),
			'width'           =>  8,
			'units'           => 'in',
			'small_height_px' =>  266/2,
			'small_width_px'  =>  240/2,
			'large_height_px' =>  1330/2,
			'large_width_px'  =>  1200/2,
			'imgfile'         => 'jk_keller-201910_6-tantamount-catalina_6',
			'offset_top_px'   =>  round(($max_horizon_offset - 92)/2),
			'location'        => 'digital',
			'status'          => '',
		],
		[
			'id'              => 'jkk_201910_7',
			'title'           => 'Tantamount Mac Catalina',
			'subtitle'        => '#7',
			'slug'            => 'catalina_7',
			'medium'          => 'print on cut aluminum',
			'sort_date'       => '2019_10_07',
			'nice_date'       => '2019',
			'height'          => get_sixteenths(1330/150),
			'width'           =>  8,
			'units'           => 'in',
			'small_height_px' =>  266/2,
			'small_width_px'  =>  240/2,
			'large_height_px' =>  1330/2,
			'large_width_px'  =>  1200/2,
			'imgfile'         => 'jk_keller-201910_7-tantamount-catalina_7',
			'offset_top_px'   =>  round(($max_horizon_offset - 92)/2),
			'location'        => 'digital',
			'status'          => '',
		],
		[
			'id'              => 'jkk_201910_8',
			'title'           => 'Tantamount Mac Catalina',
			'subtitle'        => '#8',
			'slug'            => 'catalina_8',
			'medium'          => 'print on cut aluminum',
			'sort_date'       => '2019_10_08',
			'nice_date'       => '2019',
			'height'          => get_sixteenths(1330/150),
			'width'           =>  8,
			'units'           => 'in',
			'small_height_px' =>  266/2,
			'small_width_px'  =>  240/2,
			'large_height_px' =>  1330/2,
			'large_width_px'  =>  1200/2,
			'imgfile'         => 'jk_keller-201910_8-tantamount-catalina_8',
			'offset_top_px'   =>  round(($max_horizon_offset - 92)/2),
			'location'        => 'digital',
			'status'          => '',
		],

	],
];

?>
