<?php

$series_fucking_windows = [
	'slug'        => 'fucking_windows',
	'js'          => null,
	'title'       => 'Fucking-Windows.com',
	'nice_date'   => '',
	'status'      => '',
	'description' => 'Repetitive juvenile behavior via HTML & CSS.',
	'notes'       => '',
];

$collection_fucking_windows = [
	'path'    => 'o__o/{collection}/{slug}',
	'sort'    => '-id',
	'extends'          => '{extends}',
	'series_slug'      => $series_fucking_windows['slug'],
	'series_title'     => $series_fucking_windows['title'],
	'js'               => $series_fucking_windows['js'],
	'items'   => [
		[
			'extends'     => '_layouts.single-image_viewer',
			'id'          => 'jkk_',
			'title'       => 'I ♥ Fucking Windows',
			'subtitle'    => '',
			'slug'        => 'hand_sex',
			'medium'      => 'website',
			'date'        => '2010',
			'height'      => '',
			'width'       => '',
			'units'       => '',
			'description' => 'Juvenile behavior via CSS',
		],
		[
			'extends'     => '_layouts.single-image_viewer',
			'id'          => 'jkk_',
			'title'       => 'Fucking Patterned Windows',
			'subtitle'    => '',
			'slug'        => 'burberry',
			'medium'      => 'website',
			'date'        => '2010',
			'height'      => '',
			'width'       => '',
			'units'       => '',
			'description' => 'Pattern recognition via CSS',
		],
		[
			'extends'     => '_layouts.single-image_viewer',
			'id'          => 'jkk_',
			'title'       => 'Fucking Windows Light Up My Life',
			'subtitle'    => '',
			'slug'        => 'light_source',
			'medium'      => 'website',
			'date'        => '2010',
			'height'      => '',
			'width'       => '',
			'units'       => '',
			'description' => 'Shady behavior via CSS',
		],
		[
			'extends'     => '_layouts.single-image_viewer',
			'id'          => 'jkk_',
			'title'       => 'Nom Nom Fucking Bacon Windows',
			'subtitle'    => '',
			'slug'        => 'eating_bacon',
			'medium'      => 'website',
			'date'        => '2010',
			'height'      => '',
			'width'       => '',
			'units'       => '',
			'description' => 'Don’t eat bacon via CSS',
		],
		[
			'extends'     => '_layouts.single-image_viewer',
			'id'          => 'jkk_',
			'title'       => 'Destroying Fucking Windows Documents',
			'subtitle'    => '',
			'slug'        => 'shredder',
			'medium'      => 'website',
			'date'        => '2010',
			'height'      => '',
			'width'       => '',
			'units'       => '',
			'description' => 'Repetitive office behavior via CSS',
		],
		[
			'extends'     => '_layouts.single-image_viewer',
			'id'          => 'jkk_',
			'title'       => 'Fucking Windows is killing my eyes!',
			'subtitle'    => '',
			'slug'        => 'op_art_parallax',
			'medium'      => 'website',
			'date'        => '2010',
			'height'      => '',
			'width'       => '',
			'units'       => '',
			'description' => 'Seizure inducing behavior via CSS',
		],
	],

];
?>
