<?php

$series_layered_wax = [
	'slug'        => 'layered_wax',
	'js'          => null,
	'title'       => 'I’ve Been Thinking of You for a While',
	'nice_date'   => '2008–2017',
	'status'      => '',
	'description' => '',
	'notes'       => 'collab with <a href="https://fromkeetra.com/and-yet/">Keetra Dean Dixon</a> (generally)',
	'to_dos'      => '',
];

$collection_layered_wax = [
	'path'    => 'o__o/{collection}/{slug}',
	'sort'    => '-id',
	'extends'          => '{extends}',

	'series_info'         => $series_layered_wax,

	'items'   => [
		[
			'extends'     => '_layouts.single-image_viewer',
			'id'          => 'jkkdd_',
			'title'       => 'THEN AGAIN',
			'subtitle'    => '',
			'slug'        => 'then_again',
			'medium'      => 'wax and acrylic paint',
			'date'        => '2017',
			'height'      => '26',
			'width'       => '51.5',
			'depth'       => '7.5',
			'units'       => 'in',
			'description' => '<p>commissioned by the Stedelijk Musuem Breda for <cite class="exhibition">Wonderlijk weefsel</cite> exhibtion</p><p>collab with <a href="http://fromkeetra.com">Keetra Dean Dixon</a></p>',
			'status'      => 'Stedelijk Musuem Breda',
		],
		[
			'extends'     => '_layouts.single-image_viewer',
			'id'          => 'jkkdd_',
			'title'       => 'THEN AGAIN (Specimen #1)',
			'subtitle'    => '',
			'slug'        => 'then_again-specimen-1',
			'medium'      => 'wax and acrylic paint',
			'date'        => '2017',
			'height'      => '',
			'width'       => '',
			'depth'       => '',
			'units'       => '',
			'description' => '<p>collab with <a href="http://fromkeetra.com">Keetra Dean Dixon</a></p>',
			'status'      => '',
		],
		[
			'extends'     => '_layouts.single-image_viewer',
			'id'          => 'jkkdd_',
			'title'       => 'THEN AGAIN (Specimen #2)',
			'subtitle'    => '',
			'slug'        => 'then_again-specimen-2',
			'medium'      => 'wax and acrylic paint',
			'date'        => '2017',
			'height'      => '',
			'width'       => '',
			'depth'       => '',
			'units'       => '',
			'description' => '<p>collab with <a href="http://fromkeetra.com">Keetra Dean Dixon</a></p>',
			'status'      => '',
		],
		[
			'extends'     => '_layouts.single-image_viewer',
			'id'          => 'jkkdd_',
			'title'       => 'Suddenly',
			'subtitle'    => '',
			'slug'        => 'suddenly',
			'medium'      => 'wax and acrylic paint',
			'date'        => '2011',
			'height'      => '',
			'width'       => '',
			'depth'       => '',
			'units'       => '',
			'description' => '<p>collab with <a href="http://fromkeetra.com">Keetra Dean Dixon</a></p>',
			'status'      => 'D.C. person?',
			'notes'       => '',
		],
		[
			'extends'     => '_layouts.single-image_viewer',
			'id'          => 'jkkdd_',
			'title'       => 'Suddenly (Specimen #1)',
			'subtitle'    => '',
			'slug'        => 'suddenly-specimen-1',
			'medium'      => 'wax and acrylic paint',
			'date'        => '2011',
			'height'      => '',
			'width'       => '',
			'depth'       => '',
			'units'       => '',
			'status'      => '',
			'description' => '<p>collab with <a href="http://fromkeetra.com">Keetra Dean Dixon</a></p>',
			'notes'       => '',
		],
		[
			'extends'     => '_layouts.single-image_viewer',
			'id'          => 'jkkdd_',
			'title'       => 'Suddenly (Specimen #2)',
			'subtitle'    => '',
			'slug'        => 'suddenly-specimen-2',
			'medium'      => 'wax and acrylic paint',
			'date'        => '2011',
			'height'      => '',
			'width'       => '',
			'depth'       => '',
			'units'       => '',
			'description' => '<p>collab with <a href="http://fromkeetra.com">Keetra Dean Dixon</a></p>',
			'status'      => 'gift? sold?',
			'notes'       => '',
		],
		[
			'extends'     => '_layouts.single-image_viewer',
			'id'          => 'jkkdd_',
			'title'       => 'And Yet',
			'subtitle'    => '',
			'slug'        => 'and_yet',
			'medium'      => 'wax and acrylic paint',
			'date'        => '2011',
			'height'      => '',
			'width'       => '',
			'depth'       => '',
			'units'       => '',
			'byline'      => '',
			'description' => '<p>collab with <a href="http://fromkeetra.com">Keetra Dean Dixon</a></p>',
			'status'      => 'Chattanooga',
			'notes'       => '',
		],
		[
			'extends'     => '_layouts.single-image_viewer',
			'id'          => 'jkkdd_',
			'title'       => 'And Yet (Specimen #1)',
			'subtitle'    => '',
			'slug'        => 'and_yet-specimen-1',
			'medium'      => 'wax and acrylic paint',
			'date'        => '2011',
			'height'      => '',
			'width'       => '',
			'depth'       => '',
			'units'       => '',
			'byline'      => '',
			'description' => '<p>collab with <a href="http://fromkeetra.com">Keetra Dean Dixon</a></p>',
			'status'      => '',
			'notes'       => '',
		],
		[
			'extends'     => '_layouts.single-image_viewer',
			'id'          => 'jkkdd_',
			'title'       => 'And Yet (Specimen #2)',
			'subtitle'    => '',
			'slug'        => 'and_yet-specimen-2',
			'medium'      => 'wax and acrylic paint',
			'date'        => '2011',
			'height'      => '',
			'width'       => '',
			'depth'       => '',
			'units'       => '',
			'byline'      => '',
			'description' => '<p>collab with <a href="http://fromkeetra.com">Keetra Dean Dixon</a></p>',
			'status'      => '',
			'notes'       => '',
		],
		[
			'extends'     => '_layouts.single-image_viewer',
			'id'          => 'jkk_',
			'title'       => 'Only',
			'subtitle'    => '',
			'slug'        => 'only',
			'medium'      => 'wax, acrylic paint, cinder blocks, and oil paint',
			'date'        => '2011',
			'height'      => '48',
			'width'       => '21',
			'depth'       => '12',
			'units'       => 'in',
			'status'      => 'garage',
			'notes'       => 'baltimore exhibition',
		],
		[
			'extends'     => '_layouts.single-image_viewer',
			'id'          => 'jkk_',
			'title'       => 'Only (Specimen)',
			'subtitle'    => '',
			'slug'        => 'only-specimen',
			'medium'      => 'wax, acrylic paint',
			'date'        => '2011',
			'height'      => '',
			'width'       => '',
			'depth'       => '',
			'units'       => 'in',
			'status'      => 'sold',
			'notes'       => '',
		],
		[
			'extends'     => '_layouts.single-image_viewer',
			'id'          => 'jkkdd_',
			'title'       => 'Become',
			'subtitle'    => '(orange)',
			'slug'        => 'become-orange',
			'medium'      => 'wax, acrylic paint, and spray foam',
			'date'        => '2009',
			'height'      => '24',
			'width'       => '13',
			'depth'       => '7',
			'units'       => 'in',
			'description' => '<p>collab with <a href="http://fromkeetra.com">Keetra Dean Dixon</a></p>',
			'status'      => 'garage',
			'notes'       => 'MAD Museum exhibition, Obama exhibition',
		],
		[
			'extends'     => '_layouts.single-image_viewer',
			'id'          => 'jkkdd_',
			'title'       => 'Become (Specimen)',
			'subtitle'    => '',
			'slug'        => 'become-orange-specimen',
			'medium'      => 'wax and acrylic paint',
			'date'        => '2009',
			'height'      => '',
			'width'       => '',
			'depth'       => '',
			'units'       => 'in',
			'description' => '<p>collab with <a href="http://fromkeetra.com">Keetra Dean Dixon</a></p>',
			'status'      => 'nfs',
			'notes'       => 'MAD Museum exhibition, Obama exhibition',
		],
		[
			'extends'     => '_layouts.single-image_viewer',
			'id'          => 'jkkdd_',
			'title'       => 'Become',
			'subtitle'    => '(green)',
			'slug'        => 'become-green',
			'medium'      => 'wax, acrylic paint, and spray foam',
			'date'        => '2009',
			'height'      => '24',
			'width'       => '13',
			'depth'       => '7',
			'units'       => 'in',
			'description' => '<p>collab with <a href="http://fromkeetra.com">Keetra Dean Dixon</a></p>',
			'status'      => 'destroyed',
			'notes'       => '',
		],
		[
			'extends'     => '_layouts.single-image_viewer',
			'id'          => 'jkkdd_',
			'title'       => 'Throughout',
			'subtitle'    => '',
			'slug'        => 'throughout',
			'medium'      => 'wax, acrylic paint, and spray foam',
			'date'        => '2008',
			'height'      => '54',
			'width'       => '14',
			'depth'       => '6',
			'units'       => 'in',
			'description' => '<p>collab with <a href="http://fromkeetra.com">Keetra Dean Dixon</a></p>',
			'status'      => 'melted',
			'notes'       => '3d type exhibition, Naona',
		],
	],

];
?>
